README.md

Added badges for Travis CI and a placeholder for Coveralls for the code
coverage. Also fixed a typo.
Resolves #7

Add badges and fix typo

---

.gitignore
.travis.yml
apps/finance/.solcover.js
apps/finance/contracts/Finance.sol
apps/finance/package-lock.json
apps/finance/package.json
apps/fundraising/.solcover.js
apps/fundraising/contracts/Fundraising.sol
apps/fundraising/package-lock.json
apps/fundraising/package.json
apps/group/.solcover.js
apps/group/package-lock.json
apps/group/package.json
apps/token-manager/.solcover.js
apps/token-manager/package-lock.json
apps/token-manager/package.json
apps/vault/.solcover.js
apps/vault/package-lock.json
apps/vault/package.json
apps/voting/.solcover.js
apps/voting/package-lock.json
apps/voting/package.json
package-lock.json
package.json
shared/test-helpers/run-coverage.sh
shared/test-helpers/testrpc.sh

Closes #6 
Adds test coverage as part of CI process

[WIP] Add test coverage

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Closes #18 
Merge when 👌 and acceptable.

Add event on `changeMinAcceptQuorumPct`

---

apps/fundraising/contracts/Fundraising.sol

Assert correct sale period in calculate price

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

Fix budget after decreasing below spent amount

---

apps/finance/test/finance.js
apps/fundraising/contracts/Fundraising.sol
apps/fundraising/test/fundraising.js
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/test/tokenmanager.js

Changes in multiple apps to increase coverage

Increase test coverage

---

apps/finance/.soliumrc.json
apps/finance/contracts/Finance.sol
apps/finance/package-lock.json
apps/finance/package.json
apps/fundraising/.soliumrc.json
apps/fundraising/contracts/Fundraising.sol
apps/fundraising/package-lock.json
apps/fundraising/package.json
apps/group/.soliumrc.json
apps/group/contracts/Group.sol
apps/group/package-lock.json
apps/group/package.json
apps/token-manager/.soliumrc.json
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/package-lock.json
apps/token-manager/package.json
apps/vault/.soliumrc.json
apps/vault/contracts/Vault.sol
apps/vault/package-lock.json
apps/vault/package.json
apps/voting/.soliumrc.json
apps/voting/contracts/Voting.sol
apps/voting/package-lock.json
apps/voting/package.json

Update linter and assert explicit function visibility modifiers

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

To be able to deposit ERC20 tokens with `approveAndCall`.
Closes #56.

finance: Add receiveApproval function

---

apps/finance/contracts/Finance.sol
apps/finance/package-lock.json
apps/finance/package.json
apps/finance/test/TestFinance.sol
apps/finance/test/mocks/ExecutionTarget.sol
apps/finance/test/mocks/FinanceMock.sol
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/package-lock.json
apps/token-manager/package.json
apps/token-manager/test/TestTokenManager.sol
apps/token-manager/test/mocks/ExecutionTarget.sol
apps/vault/contracts/Vault.sol
apps/vault/package-lock.json
apps/vault/package.json
apps/vault/test/TestVault.sol
apps/voting/contracts/Voting.sol
apps/voting/package-lock.json
apps/voting/package.json
apps/voting/test/TestVoting.sol
apps/voting/test/mocks/ExecutionTarget.sol
future-apps/fundraising/contracts/Fundraising.sol
future-apps/fundraising/package-lock.json
future-apps/fundraising/package.json
future-apps/fundraising/test/TestFundraising.sol
future-apps/fundraising/test/mocks/FundraisingMock.sol

truffle & solc version update + view/pure fn

---

.gitignore
apps/finance/contracts/Finance.sol
apps/finance/package-lock.json
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/package-lock.json
apps/vault/contracts/Vault.sol
apps/vault/package-lock.json
apps/voting/contracts/Voting.sol
apps/voting/package-lock.json
lerna.json
templates/dev/contracts/DevTemplate.sol
templates/dev/contracts/Imports.sol
templates/dev/contracts/misc/Migrations.sol
templates/dev/migrations/1_initial_migration.js
templates/dev/migrations/2_deploy.js
templates/dev/package-lock.json
templates/dev/package.json
templates/dev/truffle.js

Requires merging https://github.com/aragon/aragonOS/pull/215 and releasing aOS `v3.0.2`

Implement DevTemplate and transition to new roles name scheme

---

templates/tokens/contracts/MintableToken.sol
templates/tokens/contracts/TokenFactory.sol
templates/tokens/contracts/misc/Migrations.sol
templates/tokens/index.js
templates/tokens/migrations/1_initial_migration.js
templates/tokens/migrations/2_deploy.js
templates/tokens/package.json
templates/tokens/readme.md
templates/tokens/truffle.js

Easy way to deploy tokens to be used in test networks.
Will need to publish a version of the npm package after merge.

Tokens template

---

templates/dev/contracts/DevTemplate.sol
templates/dev/migrations/2_deploy.js

Makes it easier to Do Things<sup>TM</sup> with the DAO, e.g. set up new votes during the migration.

Dev template: log installed apps

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Besides, it's more consistent style with the rest of the function.
Added one test for can execute failure.

voting: Minor optizimation in canExecute

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

It doesn't make sense a Vote with minimum threshold of 0 (it would
always pass).
Besides, added some tests for wrong initializations.

voting: Check minAcceptQuorum

---

templates/beta/contracts/BetaTemplateBase.sol
templates/beta/contracts/DemocracyTemplate.sol
templates/beta/contracts/Imports.sol
templates/beta/contracts/MultisigTemplate.sol
templates/beta/contracts/misc/Migrations.sol
templates/beta/index.js
templates/beta/migrations/1_initial_migration.js
templates/beta/migrations/2_deploy.js
templates/beta/package-lock.json
templates/beta/package.json
templates/beta/readme.md
templates/beta/truffle.js

See [readme](https://github.com/aragon/aragon-apps/blob/beta-template/templates/beta/readme.md)

Implement and deploy Aragon 0.5 Beta templates

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Voting: add getter for voter status in a vote

---

apps/finance/package-lock.json
apps/finance/package.json
apps/token-manager/package.json
apps/vault/package-lock.json
apps/vault/package.json
apps/voting/package-lock.json
apps/voting/package.json

Required for https://github.com/aragon/aragon-apps/pull/104 to build properly.

Upgrade to @aragon/os 3.0.5

---

apps/finance/contracts/Finance.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

Fix missing view/pure modifiers

---

apps/finance/contracts/Finance.sol
apps/finance/package.json
apps/voting/contracts/Voting.sol
apps/voting/package.json

Needs aragonOS v3.0.6:
https://github.com/aragon/aragonOS/pull/242

Add SafeMath for uint64 in Voting and Finance apps

---

templates/beta/contracts/Imports.sol

@sohkai You were right once again, it could not be removed ;-)

templates: restore Imports workaround

---

templates/demo/migrations/2_deploy.js
templates/demo/package.json
templates/dev/contracts/DevTemplate.sol
templates/dev/ipfs.js
templates/dev/migrations/2_deploy.js
templates/dev/package.json

Rewires the demo template to reuse the dev template too :).

Dev and Demo templates: add Token Manager

---

templates/demo/migrations/2_deploy.js
templates/demo/package.json
templates/dev/contracts/DevTemplate.sol
templates/dev/ipfs.js
templates/dev/migrations/2_deploy.js
templates/dev/package.json

Similar to #131, and requires it.

Dev and Demo template: add Finance

---

apps/voting/app/.eslintrc
apps/voting/app/package.json
apps/voting/app/src/components/NewVotePanelContent.js
apps/voting/app/src/components/VotesTable.js
apps/voting/app/src/screens/Votes.js
apps/voting/app/yarn.lock

Adds the same `.eslintrc` as the dapp's to voting for peace of mind ✌️

Voting: add ESLint to app

---

apps/token-manager/app/.babelrc
apps/token-manager/app/.eslintrc
apps/token-manager/app/package.json
apps/token-manager/app/yarn.lock

Does the same as #120 and #121 but for the Token Manager.

TokenManager: add babel, ESLint

---

apps/token-manager/app/public/index.html
apps/token-manager/app/src/components/HolderRow.js
apps/token-manager/app/src/components/SideBar.js
apps/token-manager/app/src/screens/Holders.js

Addresses the comments I had on the original PR.

TokenManager: PR fixes

---

templates/beta/package.json

templates: Fix npm test

---

templates/dev/contracts/DevTemplate.sol

Should fix reverting issues on new payments on Finance.

Dev template: add permissions for finance on vault

---

apps/vault/contracts/Vault.sol
apps/vault/contracts/connectors/standards/ERC777.sol
apps/vault/test/TestVault.sol
apps/vault/test/tokens/SimpleERC20.sol
apps/vault/test/tokens/SimpleERC777.sol
apps/vault/test/vault.js

Try to make vault tests work

---

apps/finance/arapp.json
apps/finance/artifact.json
apps/token-manager/arapp.json
apps/voting/arapp.json

I've added the hand-fixed version of Finance's artifacts.json for now, so we can deploy off of that.

Apps: publish 1.0.3

---

apps/finance/app/package.json
apps/finance/app/src/script.js
apps/finance/app/src/testnet.js
apps/finance/app/yarn.lock

Testnet tokens are now added to the balances list for each DAO automatically on Finance installation and every event thereafter.

Finance load test tokens

---

apps/voting/app/src/App.js
apps/voting/app/src/abi/token-balanceof.json
apps/voting/app/src/abi/token-decimals.json
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/components/VoteRow.js
apps/voting/app/src/components/VoteSummary.js
apps/voting/app/src/index.js
apps/voting/app/src/math-utils.js
apps/voting/app/src/rxjs.js
apps/voting/app/src/script.js
apps/voting/app/src/utils/provideNetwork.js
apps/voting/app/src/vote-settings.js
apps/voting/app/src/vote-utils.js

Fixes for launch:
* Removes dummy data
* Fixes NaNs from showing up
* Asks contracts about user balances and if they can vote
* Use rinkeby etherscan URL

Voting: launch fixes

---

apps/token-manager/test/tokenmanager.js
apps/voting/test/voting.js

Fix broken tests

---

apps/finance/app/src/components/Transfers.js

Fixes #192.
💔 non-checksummed addresses and checksummed addresses.

Finance: fix filtering by token not showing any transfers

---

apps/finance/app/src/components/Transfers.js
apps/finance/app/src/lib/math-utils.js
apps/finance/app/src/web3-utils.js
apps/token-manager/app/src/math-utils.js

And non-checksummed addresses bite us again...
Also fixes the round function that cause it to show 0 rather than the real value.

Finance: fix transfer amounts not showing up correctly

---

apps/voting/app/src/components/VotesTable.js

Voting: add progress header in table of open votes

---

apps/finance/app/src/script.js

Web3 comes back to bite us again.
Apparently it's not very good at internal events, or just `Vault` events in general.
Fixes the background script so that even Vault event triggers a token refresh, and if no token is given, it defaults to refreshing the ETH amount.

Finance: fix refreshing of Vault's ETH on Vault events

---

apps/finance/app/src/App.js
apps/finance/app/src/components/NewTransfer.js

Finance: fix selection of tokens when creating a new transfer

---

apps/voting/app/src/components/NewVotePanelContent.js

Between 538cf7e
and 5236de5
I like the second one more.

Voting: add warning text for automatic voting when creating a vote

---

apps/voting/app/src/App.js
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/script.js

Also defaults users' votes to be auto executing if they decide a vote. We can have this until we add the necessary UI inputs to control this behaviour.

Voting: fix execution status

---

apps/voting/app/src/App.js

Voting: add vote id to sidepanel title

---

apps/finance/app/package-lock.json
apps/finance/contracts/Finance.sol
apps/finance/test/finance.js
apps/finance/yarn.lock

Allows the UI to get references for one-off, immediate payments.
Transactions created by an actual saved payment will have the same reference, but I think that still makes sense.

Finance: add reference to immediate payments

---

apps/finance/app/package.json
apps/finance/app/src/components/NewTransfer.js
apps/finance/app/src/components/Transfers.js
apps/finance/app/src/web3-utils.js
apps/finance/app/yarn.lock
apps/token-manager/app/package.json
apps/token-manager/app/src/components/Panels/AssignVotePanelContent.js
apps/token-manager/app/src/web3-utils.js
apps/token-manager/app/yarn.lock

Finance, TokenManager: add address input validation

---

apps/finance/app/src/components/NewTransfer.js
apps/token-manager/app/src/components/Panels/AssignVotePanelContent.js
apps/voting/app/src/components/NewVotePanelContent.js

Small hack with `setTimeout()` to wait until the fields are slightly on screen before asking them to focus (otherwise it doesn't focus).

Apps: try to focus on first input field of their side panels when opening

---

apps/finance/app/src/lib/utils.js

Finance: Add '-' in outgoing transactions

---

apps/finance/contracts/Finance.sol
apps/finance/package.json
apps/finance/test/finance.js
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/package.json
apps/token-manager/test/tokenmanager.js
apps/voting/contracts/Voting.sol
apps/voting/package.json
apps/voting/test/voting.js
templates/beta/package.json
templates/demo/package.json
templates/dev/package.json

Restrict some functions before app is initialized

---

apps/finance/contracts/Finance.sol
apps/token-manager/contracts/TokenManager.sol

Review SafeMath for all apps

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Closes #189.
Mostly imported from commit https://github.com/aragon/aragon-apps/pull/238/commits/3dd43692350140b7307410bd77e7376f63e22900

Allow to create a vote and not cast a vote immediately

---

apps/finance/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/vault/truffle.js
apps/voting/package.json
future-apps/fundraising/package-lock.json
future-apps/fundraising/package.json
future-apps/payroll/package.json
package.json
shared/test-helpers/ganache-cli.sh
shared/test-helpers/run-coverage.sh
templates/beta/package.json

Simplifies our scripting a little bit.

Run solidity-coverage from ganache-cli.sh

---

apps/finance/artifact.json
apps/finance/contracts/Finance.sol

> NewTransaction event should include _amount

Finance: add amount to NewTransaction event

---

apps/finance/contracts/Finance.sol

> executePayment pass payment amount into authP params

Finance: pass amount to auth params for executePayment()

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

Finance: require deposits to have value

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

> getBudget returns remainingBudget as well

Finance: make getRemainingBudget() public so getBudget() only returns budget settings

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

> Payment repeat number is not recorded in the transaction

Finance: include payment repeat number in transactions

---

apps/voting/contracts/Voting.sol
apps/voting/test/mocks/VotingMock.sol
apps/voting/test/voting.js

- Remove unused first index for Votes
- Minor style change
- Simplify `_isValuePct` function

Voting minor improvements

---

apps/token-manager/contracts/TokenManager.sol

Fix typo in cliff comment diagram.

---

future-apps/payroll/README.md

Fixing links in payroll readme (#327)

---

apps/survey/app/src/App.js
apps/survey/app/src/components/Survey/SurveyDetails.js
apps/survey/app/src/components/Survey/VotesCast.js
apps/survey/app/src/components/Survey/VotesHistory.js
apps/survey/app/src/components/SurveyCard/SurveyCard.js
apps/survey/app/src/components/SurveyOptions/SurveyOptions.js
apps/survey/app/src/components/Surveys/Surveys.js
apps/survey/app/src/demo-state.js
apps/survey/app/src/option-utils.js
apps/survey/app/src/rxjs.js
apps/survey/app/src/script.js
apps/survey/app/src/survey-settings.js

Also modifies the frontend schema to be consistent with what the background script will give.

Survey background script with more data

---

apps/finance/package.json
apps/survey/package-lock.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json

Should we also build the frontend?

Add prepublishOnly hook to all apps

---

shared/test-helpers/package.json

So in case of npm download we have latest changes.

Update test-helpers version

---

LICENSE
apps/finance/app/package.json
apps/finance/contracts/Finance.sol
apps/finance/package.json
apps/survey/app/package.json
apps/survey/contracts/Survey.sol
apps/survey/package.json
apps/token-manager/app/package.json
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/package.json
apps/vault/package.json
apps/voting/app/package.json
apps/voting/contracts/Voting.sol
apps/voting/package.json
package.json

Not sure if this really matters, and the way the repo is set up makes this a bit of a pain, but I've tried to make it so that both GPL and AGPL are included.
If you like this, I'll do it for the rest of the apps too.

Update licenses to include both GPL and AGPL

---

apps/finance/app/package.json
apps/survey/app/package.json
apps/token-manager/app/package.json
apps/voting/app/package.json

Upgrade parcel and pin styled-components

---

apps/finance/contracts/Finance.sol

Fixes #333.
@izqui Don't remember exactly how the string is passed into the voting app (I assume it's the same one), so will have to test if the recipient address also shows up there.

Finance: add receiver to radspec string of newPayment()

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

Finance: add transitionsPeriod to fallback

---

apps/finance/contracts/Finance.sol

See https://github.com/aragon/aragonOS/issues/327.

Finance: make fallback external

---

apps/finance/arapp.json
apps/finance/contracts/Finance.sol
apps/finance/package.json

Needs: https://github.com/aragon/aragonOS/pull/377

Finance: add `hasBudget` to `CHANGE_BUDGETS_ROLE`

---

apps/voting/contracts/Voting.sol

Voting: reorder min quorum sanity checks for clarity

---

apps/survey/contracts/Survey.sol
apps/survey/test/survey.js

Survey check in options master

---

apps/token-manager/contracts/TokenManager.sol
apps/token-manager/test/tokenmanager.js

Token Manager: stop logging holders

---

apps/survey/contracts/Survey.sol

Survey: add acceptableMinParticipationPct modifier

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Voting: make inequality strict

---

apps/voting/test/voting.js

Address PR #459 comments. (There was one missing)

Voting: make inequality strict, tests

---

apps/voting/app/src/App.js
apps/voting/app/src/abi/token-balanceOfAt.json
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/utils.js

Related issue: https://github.com/aragon/aragon-apps/issues/216

Voting panel: execute + change vote

---

apps/voting/app/src/App.js
apps/voting/app/src/abi/token-balanceOfAt.json
apps/voting/app/src/components/VotePanelContent.js

Oops, forgot to use `balanceOfAt()` earlier 😅

Voting: fix VotePanel not using balanceOfAt()

---

apps/voting/app/package.json
apps/voting/app/src/components/VoteStatus.js

Voting fixes

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js
apps/vault/contracts/Vault.sol
apps/vault/test/vault.js

Vault: remove `_from` parameter in `deposit()`

---

apps/token-manager/app/.eslintrc
apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/Panels/AssignVotePanelContent.js
apps/token-manager/app/src/components/SideBar.js
apps/token-manager/app/src/components/TokenBadge.js
apps/token-manager/app/src/token-settings.js
apps/token-manager/app/src/utils.js

Builds on #480.
A number of small things, changing some linting behaviour and mostly cosmetic code changes to align the Token Manager with the refactored Voting app in #483.
Easiest to review commit-by-commit.

Token Manager: small updates

---

apps/token-manager/app/src/App.js
apps/token-manager/app/src/rxjs.js
apps/token-manager/app/src/script.js

Takes the best from the other scripts :smile: :
- Use `INITIALIZATION_TRIGGER`
- Use the `retry()` helper

Token Manager: modernize background script

---

apps/finance/app/package.json
apps/survey/app/package.json
apps/token-manager/app/package.json
apps/voting/app/package.json

Seems like nothing's wrong with them after the upgrade :D

Update @aragon/client to v1.0.0

---

apps/voting/app/src/App.js
apps/voting/app/src/components/VoteSuccess.js
apps/voting/app/src/vote-utils.js

Closes https://github.com/aragon/aragon-apps/issues/506.
[🙈`open` is actually in the `data`](https://github.com/aragon/aragon-apps/blob/master/apps/voting/app/src/App.js#L166)

Voting: fix misrepresentation of open votes as closed votes

---

apps/finance/app/src/script.js
apps/survey/app/src/script.js
apps/voting/app/src/App.js
apps/voting/app/src/components/VoteSummary.js
apps/voting/app/src/rxjs.js
apps/voting/app/src/script.js
apps/voting/app/src/vote-settings.js
apps/voting/app/src/vote-utils.js

Updates the apps after the contract changes in #434.
Fixes #465.

Update app scripts

---

apps/finance/app/package.json
apps/finance/app/src/App.js
apps/finance/app/src/components/TransferRow.js
apps/finance/app/src/index.js
apps/finance/app/src/lib/provideNetwork.js
apps/finance/app/src/lib/utils.js
apps/finance/app/src/script.js
apps/survey/app/package.json
apps/survey/app/src/App.js
apps/survey/app/src/components/Creator/Creator.js
apps/survey/app/src/index.js
apps/survey/app/src/provide-network.js
apps/token-manager/app/package.json
apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/index.js
apps/voting/app/src/utils.js
apps/voting/app/src/utils/provideNetwork.js

Fixes #500.
Changes the etherscan link to the appropriate network, and also the available test tokens in finance.

Apps: use connected network details from aragon.js

---

apps/token-manager/app/package.json
apps/token-manager/app/src/screens/EmptyState.js
apps/voting/app/package.json
apps/voting/app/src/screens/EmptyState.js

Removes the annoying warning :-)

Upgrade token manager and voting to @aragon/ui 0.23

---

apps/finance/app/package.json
apps/finance/app/src/App.js
apps/finance/app/src/components/GetWindowSize.js
apps/finance/app/src/components/TransferRow.js
apps/finance/app/src/components/Transfers.js

Use the identity badge

---

apps/finance/app/src/abi/vault-events.json
apps/finance/arapp.json
apps/finance/package.json
apps/vault/package.json

Requires an on-chain upgrade for the Vault only.

Upgrade vault version

---

apps/finance/app/src/components/NewTransfer/TokenSelector.js

Finance: fix the mainnet type in the token selector

---

apps/finance/app/package.json
apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/components/NewTransfer/TokenSelector.js
apps/finance/app/src/components/TransferRow.js
apps/finance/app/src/lib/token-utils.js
apps/finance/app/src/lib/utils.js
apps/survey/app/src/utils.js
apps/token-manager/app/package.json
apps/voting/app/package.json
apps/voting/app/src/utils.js

🙈 Will also need to bump the version of `@aragon/ui` once https://github.com/aragon/aragon-ui/pull/237 is released.

Fix mainnet detection in apps

---

apps/voting/app/src/App.js
apps/voting/app/src/evmscript-utils.js
apps/voting/app/src/script.js
apps/voting/app/src/vote-utils.js

Voting: add support required to identifier

---

apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/components/VoteSummary.js

Voting: rename voting panel's quorum and support labels for clarity

---

apps/finance/app/src/App.js
apps/survey/app/src/App.js
apps/token-manager/app/src/App.js
apps/voting/app/src/App.js

This component is going to be deprecated in Aragon UI / Lorikeet.

Remove <AragonApp />

---

apps/finance/app/src/App.js
apps/token-manager/app/src/App.js
apps/voting/app/src/App.js

Vertically center empty screens

---

apps/finance/contracts/Finance.sol

Not sure how we missed this earlier 🙈

Finance: remove unnecessary memory variable

---

apps/finance/app/src/App.js

Fixes https://github.com/aragon/aragon/issues/509

Finance: order balances by ETH and then token symbol alphabetically

---

apps/token-manager/app/src/App.js
apps/voting/app/src/App.js
apps/voting/app/src/components/NewVotePanelContent.js
apps/voting/contracts/Voting.sol

Fixes https://github.com/aragon/aragon-apps/issues/583, fixes https://github.com/aragon/aragon/issues/510, fixes https://github.com/aragon/aragon/issues/516.

Voting: text clarifications

---

apps/finance/app/src/components/NewTransfer/Deposit.js

Fixes https://github.com/aragon/aragon/issues/502, fixes https://github.com/aragon/aragon/issues/500.

Finance: clarify depositing text

---

apps/finance/app/src/components/BalanceToken.js

Finance: display "?" when a token symbol is unknown

---

apps/finance/contracts/Finance.sol

feat(Finance.sol): Added _reference to @notice string for newPayment

---

apps/finance/app/src/App.js
apps/finance/app/src/script.js

Finance: incorporate period transitions into token deposit gas estimations

---

apps/finance/app/src/App.js
apps/finance/app/src/abi/token-name-bytes.json
apps/finance/app/src/abi/token-symbol-bytes.json
apps/finance/app/src/components/BalanceToken.js
apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/lib/token-utils.js
apps/finance/app/src/lib/web3-utils.js
apps/finance/app/src/script.js

Fixes https://github.com/aragon/aragon-apps/issues/561.
Fix for the token symbol in bytes32 (DAI)

bytes32 symbol

---

apps/voting/app/src/components/VotePanelContent.js

Fixes #655
Until we get the connect button accessible from anywhere.

Voting: allow non-connected accounts to vote

---

apps/finance/contracts/test/TestImports.sol
apps/finance/package.json
apps/survey/contracts/test/TestImports.sol
apps/survey/contracts/test/mocks/BadToken.sol
apps/survey/package.json
apps/token-manager/.soliumrc.json
apps/token-manager/contracts/test/TestImports.sol
apps/token-manager/package.json
apps/vault/contracts/test/TestImports.sol
apps/vault/contracts/test/mocks/KernelDepositableMock.sol
apps/vault/package.json
apps/voting/contracts/test/TestImports.sol
apps/voting/package.json

Fixes some linting errors in the CI.

chore: upgrade solium

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/contracts/test/mocks/EtherTokenConstantMock.sol
future-apps/payroll/contracts/test/mocks/PayrollMock.sol
future-apps/payroll/package-lock.json
future-apps/payroll/test/payroll_allowed_tokens.js

Fixes #649.
One thing to take into account is that right now is not possible to remove tokens from the allowed list.

Payroll: Add hard cap for allowed tokens, to avoid OOG attacks

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

Ensure all public utility functions requiring valid state enforce initialization checks.
Unsafe internal variants of these functions are provided that bypass the initialization check for optimized use inside the contract.

Finance, Token Manager, Voting: split utility getters into public and internal functions with different protection schemes

---

apps/survey/app/src/App.js
apps/survey/app/src/math-utils.js
apps/survey/app/src/script.js

Essentially https://github.com/aragon/aragon-apps/pull/695 but for Survey.

Survey: default decimals to 0 if token contract doesn't specify them

---

apps/finance/contracts/Finance.sol
apps/survey/contracts/Survey.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

It's very unlikely incrementing uint256 array lengths will be a problem (we probably have bigger ones if we ever get to the point where these overflow), but still better practice to be safe.
Also removes SafeMath from a few places where we've already done the check implicitly.

Finance: optimize SafeMath

---

apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/index.js
apps/voting/app/src/script.js

Bug fixes that were introduced by a couple of critical changes not committed to #721.
This PR addresses thouse

Voting: rxjs upgrade fixes

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/package.json

- Specify truffle dependency
- Apply external/internal functions schema (it was almost done)

Payroll: Organize internal/external functions

---

apps/voting/app/src/components/VotePanelContent.js

Reference: https://github.com/aragonone/product/issues/30

VotePanelContent: add no token cost to info card

---

apps/token-manager/contracts/TokenManager.sol

Changes the `ITokenController` methods to be `external`, as they never need to be called from within the Token Manager itself.

Token Manager: small improvements for ITokenController interface

---

apps/finance/app/src/App.js

Oops, forgot to change this when `appState`.

Finance: fix deposit gas calculations

---

apps/agent/package.json
apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json

Payroll to be upgraded separately.

chore: update apps to aragonOS 4.2.0

---

apps/agent/package.json
apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/scripts/deploy.js

Couple of small things missed in #785.

chore: small clean up for published package

---

apps/agent/package.json
apps/finance/package.json

Oops, forgot to do this when initially publishing the app versions.
Will release patch versions of Agent and Finance.

chore: update apps' dependency apps

---

apps/finance/app/src/App.js
apps/finance/app/src/components/Balances.js
apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/components/NewTransfer/Withdrawal.js
apps/token-manager/app/src/components/HolderRow.js
apps/token-manager/app/src/screens/EmptyState.js
apps/voting/app/src/components/NewVotePanelContent.js
apps/voting/app/src/components/VoteStatus.js
apps/voting/app/src/screens/EmptyState.js

Adds the non-controversial changes from https://github.com/aragon/aragon-apps/pull/795, merged with master.
cc @luisivan.

Copy improvements

---

apps/finance/app/package.json

Allows rinkeby users to see test DAI

Finance: upgrade @aragon/templates-tokens

---

apps/finance/app/src/components/Balances.js

Finance: fix double border on balance

---

apps/voting/app/package.json

Fixes the position of the `IdentityBadge` in the side panel, among other improvements.

Voting: upgrade @aragon/ui to 0.37.0

---

apps/finance/app/.babelrc
apps/survey/app/.babelrc
apps/token-manager/app/.babelrc
apps/voting/app/.babelrc

These apps already have their correct browserslist declarations in their package.jsons.

Frontends: use correct browserslist specified in package.json

---

apps/finance/app/package.json
apps/finance/app/src/components/Transfers.js

Updates to `file-saver` and fixes issue when exporting date range

Update dynamic download dep

---

apps/voting/app/package.json
apps/voting/app/src/components/VotePanel.js
apps/voting/app/src/components/VotingCard/VotingCard.js

Requires https://github.com/aragon/aragon-ui/pull/377
Fixes https://github.com/aragon/aragon-apps/issues/638

Voting countdowns: limit the units displayed

---

apps/finance/app/src/components/DateRange/DatePicker.js
apps/finance/app/src/components/DateRange/DateRangeInput.js

Implementation of https://github.com/aragon/aragon-apps/pull/847#issuecomment-493208551 :smile:

Finance: add header to date range input for clarity

---

apps/token-manager/app/src/components/LocalIdentitiesAutoComplete/LocalIdentitiesAutoComplete.js

- https://github.com/aragon/aragon.js/pull/308

Integrate local identities autocomplete with updated api

---

apps/finance/app/package.json
apps/finance/app/src/App.js
apps/finance/app/src/script.js

- Reduce sync state events to render the app loading state
- Dependent in aragon.js: https://github.com/aragon/aragon.js/pull/297
- Related issue: https://github.com/aragonone/product/issues/98

Finance - app loading state

---

apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js
apps/voting/app/src/script.js

- Builds on https://github.com/aragon/aragon-apps/pull/836
- Requires https://github.com/aragon/aragon.js/pull/297
Tries to follow the changes made on https://github.com/aragon/aragon-apps/pull/867.

Voting: display the syncing state

---

apps/voting/contracts/Voting.sol

Simply adding and polishing voting contract inline documentation.

Voting: Complete contract inline documentation

---

.travis.yml

See https://github.com/aragon/aragon/pull/856.

Travis: remove deprecated sudo

---

apps/agent/contracts/Agent.sol

Missed in https://github.com/aragon/aragon-apps/pull/651.

Agent: remove unused error constants

---

.github/autolabeler.yml

Fix autolabeler's label names

---

apps/agent/package.json

`ens-name-hash` dependency was missing

Agent: Declare ens-name-hash dependency

---

apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/AutoComplete/AutoCompleteSelected.js
apps/token-manager/app/src/components/HolderRow.js
apps/token-manager/app/src/components/InfoBoxes.js
apps/token-manager/app/src/hooks.js
apps/token-manager/app/src/screens/Holders.js

Fixes a couple of innocent linting errors, although the most important is https://github.com/aragon/aragon-apps/pull/936#issue-301636478 (which broke the app previously)

Token Manager: fix linting

---

apps/agent/package.json
apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json
future-apps/payroll/package.json

Fixes https://github.com/aragon/aragon-apps/issues/658.

Apps: upgrade testrpc-sc based on solidity-coverage@0.6.4

---

shared/minime/truffle.js

cc @0xGabi, will republish as `@aragon/apps-shared-minime@1.0.2`.

MiniMeToken: use same solc optimizer settings as apps

---

apps/finance/app/package.json
apps/finance/app/src/lib/token-utils.js
apps/finance/app/src/script.js

Reworked a few bits of the background script while working on [the Agent's](https://github.com/aragon/aragon-apps/pull/952). This keeps the two looking fairly similar, and simplifies some of the internal functions by passing less state to them.
Also fixes https://github.com/aragon/aragon-apps/issues/892.

Finance: update background script

---

apps/voting/app/src/app-state-reducer.js
apps/voting/app/src/screens/VoteDetail.js
apps/voting/app/src/script.js

Adds the date a vote became enacted as well as its transaction hash, as seen in [Figma](https://www.figma.com/file/O09HJRCFDwDTni4VE3tiRvwI/Voting?node-id=1602%3A369).
See in the Status side split:

Voting: add enacted state

---

apps/finance/app/package.json
apps/finance/app/src/components/BalanceToken.js
apps/finance/app/src/components/Balances.js
apps/finance/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/finance/app/src/components/NewTransfer/TokenSelector.js
apps/finance/app/src/components/NewTransfer/Withdrawal.js
apps/finance/app/src/components/TransfersFilters.js
apps/finance/app/src/script.js
apps/token-manager/app/package.json
apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/token-manager/app/src/components/Panels/TokenPanelContent.js
apps/voting/app/package.json
apps/voting/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/voting/app/src/components/NewVotePanel.js
apps/voting/app/src/components/SummaryBar.js
apps/voting/app/src/components/VoteCard/VoteOption.js
apps/voting/app/src/screens/VoteDetail.js
apps/voting/app/src/screens/Votes.js

Adjusts and fixes various styling issues found during design review.

Finance, Tokens, Voting: design review

---

apps/voting/app/src/components/VoteCasted.js

Fixes typo suggestion in Design review 0.8 II list

Voting: fix typo

---

apps/agent/arapp.json

Alternatively we can change the status to `beta`.
@sohkai what do you think?

Agent: remove experimental status from arapp file

---

apps/voting/app/src/screens/VoteDetail.js

Fixes https://github.com/aragon/aragon/issues/1066

Fixes voting status progress being backwards

---

apps/token-manager/app/src/components/Panels/TokenPanelContent.js

mint -> create tokens
burn -> remove

Change Tokens app copy

---

apps/voting/app/src/hooks/useVotes.js

Just an attempt to fix the app crashing, until we find the root issue.

Voting: tolerate undefined executionTargets

---

apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js

Fixes https://github.com/aragon/aragon/issues/1127.
Requires a soon-to-be-released patch from aragon.js.

Voting: specify which newVote() override to use

---

apps/voting/app/package.json
apps/voting/app/src/app-logic.js
apps/voting/app/src/components/NewVotePanel.js
apps/voting/app/src/hooks/usePanelState.js
apps/voting/app/src/screens/Votes.js

Also moved to `useSidePanelFocusOnReady()`.

Voting: update aragonUI to 1.0.0

---

apps/voting/app/src/components/VoteCard/VoteCard.js

Voting: animate card's voted indicator on focus / blur

---

apps/agent/app/package.json
apps/agent/app/src/App.js
apps/agent/app/src/components/ComingSoon.js
apps/agent/app/src/index.js
apps/finance/app/package.json
apps/finance/app/src/App.js
apps/finance/app/src/index.js
apps/token-manager/app/package.json
apps/token-manager/app/src/App.js
apps/token-manager/app/src/index.js
apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js

requires https://github.com/aragon/aragon.js/pull/408
Support dark mode in Agent, Finance, Tokens, and Voting.

Finance, Tokens, Voting: dark mode support

---

apps/voting/app/src/script.js

Missed this `web3Eth` when doing the original exponential backoff in https://github.com/aragon/aragon-apps/pull/934. Didn't realize that asking for block numbers could also fail, and they do so rather silently (only a `null` is returned, rather than erroring).

Voting: wrap attempt to fetch execution date with exponential retries

---

apps/agent/package.json
apps/agent/truffle.js
apps/finance/package.json
apps/finance/truffle.js
apps/survey/package.json
apps/survey/truffle.js
apps/token-manager/package.json
apps/token-manager/truffle.js
apps/vault/package.json
apps/vault/truffle.js
apps/voting/package.json
apps/voting/truffle.js
future-apps/payroll/package.json
future-apps/payroll/truffle.js

chore: update truffle config to shared config

---

apps/agent/arapp.json
apps/finance/arapp.json
apps/survey/arapp.json
apps/token-manager/arapp.json
apps/vault/arapp.json
apps/voting/arapp.json
future-apps/payroll/arapp.json

See [migration details](https://medium.com/the-ethereum-name-service/ens-registry-migration-bug-fix-new-features-64379193a5a).

Apps: update ENS registry address in arapp.json

---

CONTRIBUTING.md
README.md

- Update Aragon Chat links to Spectrum
- Add Spectrum link to readme

chore: update Aragon Chat links

---

apps/agent/app/src/components/Transactions.js

Agent: Fix dropdown arrow appearing on mobile on executions with 0 token transfers

---

apps/finance/app/src/script.js

Finance: format token helper script section to match Agent's

---

apps/token-manager/app/src/components/UpdateTokenPanel/UpdateTokenPanel.js

See https://github.com/aragon/aragon-apps/pull/1130#issuecomment-634867177

Tokens: remove the “max” button on assign

---

apps/survey/app/src/components/VotingPanel/VotingPanel.js

**NOT YET TESTED**
Replicates #747 for the Survey app.

Survey: add no token cost info card

---

apps/agent/app/src/components/TransactionFilters.js
apps/agent/app/src/components/Transactions.js
apps/agent/app/src/components/useDownloadData.js
apps/agent/app/src/lib/date-utils.js
apps/finance/app/src/components/Transfers.js
apps/finance/app/src/components/TransfersFilters.js

Closes #1173 
This will update the date format in the UI components and also in the CSV export. Here are the screenshots:

Agent, Finance: update date format

---

apps/voting/app/src/agreementsMockData.js
apps/voting/app/src/components/VoteDetail/DisputableActionStatus.js
apps/voting/app/src/components/VoteDetail/VoteInfoBoxes.js
apps/voting/app/src/disputable-utils.js
apps/voting/app/src/screens/VoteDetail.js

Agreements voting app: 2 – Disputable action status component

---

apps/voting/app/src/components/VoteDetail/DisputableActionStatus.js
apps/voting/app/src/components/VoteDetail/DisputableActions.js

All buttons for the avaiable disputable actions depending on the vote status and connected account

Agreements voting app: 4 – Disputable actions

---

apps/voting/app/src/components/DisputableStatusLabel.js
apps/voting/app/src/components/VoteCard/VoteCard.js

Agreements voting app: 5- Reflect disputable status on vote cards

---

apps/agent/app/src/components/useDownloadData.js

Adds a toast when the export is successfully completed on the Agent app.

Agent: Add useToast to agent export on click

---

.github/auto_assign.yml

chore: add @delfipolito to reviewers list

---

apps/voting-disputable/contracts/DisputableVoting.sol
apps/voting-disputable/contracts/test/mocks/DisputableVotingMock.sol
apps/voting-disputable/contracts/test/mocks/DisputableVotingWithoutAgreementMock.sol
apps/voting-disputable/package.json
apps/voting-disputable/test/contracts/voting_delegation.js
apps/voting-disputable/test/contracts/voting_vote.js
apps/voting-disputable/test/helpers/voting.js

voting-disputable: Use new ACL version

---

apps/agreement/contracts/Agreement.sol
apps/agreement/contracts/example/RegistryApp.sol
apps/agreement/contracts/test/mocks/disputable/AragonAppFeesCashierMock.sol
apps/agreement/contracts/test/mocks/disputable/DisputableAppMock.sol
apps/agreement/contracts/test/mocks/helpers/TokenBalanceOracle.sol

Agreement: Use new ACL version

---

apps/agreement/contracts/Agreement.sol
apps/agreement/contracts/test/mocks/disputable/DisputableAppMock.sol
apps/agreement/test/agreement/agreement_challenge.js
apps/agreement/test/agreement/agreement_rule.js
apps/agreement/test/agreement/agreement_settlement.js
apps/agreement/test/helpers/assert/assertEvent.js
apps/agreement/test/helpers/wrappers/disputable.js

Merging https://github.com/aragon/aragon-apps/pull/1199 against master

Agreement: Implement try catch

---

apps/voting-disputable/app/src/components/VoteDetail/DisputableActionStatus.js
apps/voting-disputable/app/src/components/VoteDetail/DisputablePeriod.js
apps/voting-disputable/app/src/components/VoteDetail/VoteInfoBoxes.js
apps/voting-disputable/app/src/screens/VoteDetail.js
apps/voting-disputable/app/src/script.js
apps/voting-disputable/app/src/utils.js

Disputable voting app: Show real data on challenge/settlement period

---

apps/agreement/test/agreement/agreement_activation.js
apps/agreement/test/agreement/agreement_challenge.js
apps/agreement/test/agreement/agreement_collateral.js
apps/agreement/test/agreement/agreement_dispute.js
apps/agreement/test/agreement/agreement_settlement.js
apps/agreement/test/agreement/agreement_signing.js
apps/finance/test/finance.js

Tests: Fix assert event usage

---

apps/voting-disputable/contracts/DisputableVoting.sol
apps/voting-disputable/test/contracts/voting_create.js
apps/voting-disputable/test/contracts/voting_delegation.js
apps/voting-disputable/test/contracts/voting_disputable.js
apps/voting-disputable/test/contracts/voting_gas_costs.js
apps/voting-disputable/test/contracts/voting_initialization.js
apps/voting-disputable/test/contracts/voting_settings.js
apps/voting-disputable/test/contracts/voting_vote.js
apps/voting-disputable/test/helpers/voting.js
apps/voting-disputable/truffle.js

It is recommended to review per commit

DisputableVoting: Checkpoint settings

---

apps/agreement/contracts/Agreement.sol

Depends on: https://github.com/aragon/aragonOS/pull/597

Agreement: Adapt to new IAragonApp interface

---

apps/agreement/contracts/Agreement.sol
apps/agreement/package.json
apps/agreement/test/agreement/agreement_lock_manager.js

Depends on: https://github.com/aragon/staking/pull/47
Merge after #1226 (and change PR base)

Agreement: Implement Staking ILockManager

---

apps/agreement/contracts/Agreement.sol
apps/agreement/test/agreement/agreement_close.js
apps/agreement/test/agreement/agreement_gas_cost.js

Related to https://github.com/aragon/aragonOS/pull/594

Agreement: Ignore re-closing requests

---

apps/voting-disputable/app/src/components/DisputableStatusLabel.js

Disputable voting app: Fix cancelled label

---

apps/agreement/contracts/Agreement.sol
apps/agreement/contracts/arbitration/IAragonAppFeesCashier.sol
apps/agreement/contracts/arbitration/IArbitrable.sol
apps/agreement/contracts/arbitration/IArbitrator.sol
apps/agreement/contracts/test/mocks/disputable/AragonAppFeesCashierMock.sol
apps/agreement/contracts/test/mocks/disputable/ArbitratorMock.sol
apps/agreement/contracts/test/mocks/disputable/DisputableAppMock.sol
apps/agreement/package.json
yarn.lock

This PR makes the current Agreement app compatible with the latest changes introduced in aragonOS v5.0.0-beta.8

Agreement: Update aragonOS to v5.0.0-beta.8

---

.travis.yml
apps/agreement/package.json
apps/voting-disputable/buidler.config.staking.js
apps/voting-disputable/contracts/test/TestImports.sol
apps/voting-disputable/mocks/staking/StakingImports.sol
apps/voting-disputable/package.json
yarn.lock

Applies the same tricks as Agreement. Unfortunately coverage does not work yet in a multi-solc set up.

DisputableVoting: migrate to staking 0.2.9

---

apps/agent/buidler.config.js
apps/agent/package.json
apps/agreement/package.json
apps/finance/buidler.config.js
apps/finance/package.json
apps/token-manager/buidler.config.js
apps/token-manager/package.json
apps/vault/buidler.config.js
apps/vault/package.json
apps/voting-disputable/package.json
apps/voting/buidler.config.js
apps/voting/package.json
yarn.lock

Pretty minor clean up and version alignments between the different packages.

Apps: align and polish package.json files

---

apps/voting-disputable/contracts/DisputableVoting.sol
apps/voting-disputable/test/contracts/voting_disputable.js

**MERGE AFTER #1273**
Following https://github.com/aragon/network/pull/9

DisputableVoting: Reject votes when voided

---

.github/scripts/update_deploymentfile.py
.github/workflows/release.yml

- adds stardust, andromeda and bscTest networks
- fixes update_deploymentfile to handle empty deploys.yaml file in deployments repo

New networks

---

README.md

Updated readme file to trigger the deploy job.

deploy dandelion and open enterprise apps to bscTest
