aragon/aragon-apps

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

- Change all instances where 'voting' was being used instead of 'vote'. Closes https://github.com/aragon/aragon/issues/53 after wiki documentation update.
- Logs voter stake in cast vote event. Closes #18 
- Add boolean parameter when casting a vote on whether it should be automatically executed . Closes #19

Multiple voting app small changes

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

If accidentally somebody sends tokens to Finance contract address
directly through transfer, tokens could be locked. This function
allows to send them to Vault.
Closes #57.

finance: Add function to send tokens to Vault

---

apps/finance/contracts/Finance.sol

Otherwise, `receiveApproval` can move anyone's money that has given a 0xFFF approval to the org.
Fixes issue #83

finance: Restrict receiveApproval to be called only by token

---

apps/finance/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json
future-apps/fundraising/package.json
future-apps/payroll/package.json
templates/dev/package.json
templates/tokens/package.json

Truffle@4.0.6 upgrades solidity to 0.4.19, which breaks our fixed contracts.

Pin truffle to 4.0.5

---

templates/beta/package.json
templates/demo/package.json
templates/dev/package.json
templates/tokens/package.json

At least 3.0.6 is required for the changes in `Voting` and `Finance` to compile.

Bump aragon/os version in templates

---

templates/beta/docker-compose.yml

So that we can restart the containers.
Note: it would be nice to add something like `USER geth` in the image so we don’t run geth as root.

Beta templates container: mount a local directory

---

apps/finance/contracts/Finance.sol
apps/finance/test/TestFinance.sol
apps/finance/test/finance.js
apps/finance/test/mocks/ExecutionTarget.sol
apps/finance/test/mocks/FinanceMock.sol
apps/vault/contracts/IVaultConnector.sol
apps/vault/contracts/Vault.sol
apps/vault/contracts/connectors/ERC20Connector.sol
apps/vault/contracts/connectors/ERC721Connector.sol
apps/vault/contracts/connectors/ERC777Connector.sol
apps/vault/contracts/connectors/ETHConnector.sol

Besides, rename IConnector interface to IVaultConnector

finance: Adapt to new Vault

---

templates/beta/docker-compose.yml

So it's the default and there's no need to add anything to `geth attach`.

templates: Change geth docker image data path

---

apps/finance/app/package.json
apps/finance/app/yarn.lock
apps/token-manager/app/package.json
apps/token-manager/app/yarn.lock
apps/voting/app/package.json
apps/voting/app/yarn.lock

Updates to `@aragon/client@v1.0.0-beta.5` and updates lock files to avoid depending on older version of `@aragon/messenger`.

Apps: fix @aragon/client version and lock files

---

apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/script.js
apps/voting/app/src/vote-utils.js
apps/voting/app/yarn.lock

Generates a description from the vote callscript if specified.
We might want to change the description format. Currently each step in the transaction path contains:
```js
{
to: string,
data: string,
?description: string,
?name: string,
?identifier: string
}
```
And we render each step on a new line in chronological order, where each like is ``<name> (<address>): <description>``, for example:
>Token Manager (0xbabe): Execute action as token holder
>Token Manager (0xdeadbeef): Mint 1 tokens for 0xebefbbabbe
Note that the above example is super hypothetical

Radspec voting

---

apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/components/VoteRow.js
apps/voting/app/src/screens/Votes.js
apps/voting/app/src/script.js
apps/voting/app/src/vote-settings.js
apps/voting/app/yarn.lock

The scripts shouldn't do this, as they'd have to check all the time. Instead, we replicate the logic client-side based on the current time and whether or not the vote's been executed.

Voting: calculate if votes are open client-side

---

apps/finance/app/src/components/Balances.js

Add an empty, transparent item to make sure the balances box is already at the right height:

Better loading state in the finance app

---

apps/token-manager/app/src/components/SideBar.js

Avoids cases like
Where the last 1% is from a rounding issue, but not really representative of the token ownership.

TokenManager: oly show rest in partition graph if all not owners are present in graph

---

apps/finance/app/src/components/Balances.js

Fixes #190.
Fixes a race condition with getting the right tokens to convert fiat amounts for.
@Smokyish this should work a lot more reliably now. We can still hide it, if you'd like.

Finance: fix fiat conversion for tokens

---

apps/voting/app/src/components/VoteRow.js

Fixes the extra padding in the description when no question is available.

Voting: fix alignment of description in VoteRow if no question

---

apps/finance/app/src/components/TransferRow.js
apps/finance/app/src/lib/utils.js

Use `isIncoming` to identify when it's an incoming or outgoing payment.

Finance: correctly identity outgoing transfers

---

apps/finance/app/.gitignore
apps/finance/app/package.json
apps/token-manager/app/.gitignore
apps/token-manager/app/package.json
apps/voting/app/.gitignore
apps/voting/app/package.json

Fixes #239.
So it looks like parcel 1.7.0 (originally those commands were for 1.6.2) either removed or changed the behaviour of `-o` (and the bundler's default behaviour without that flag set).
Specifying `-o script.js` actually produces `public/script.js.js` now, but the default just works<sup>TM</sup> :D.

UIs: fix parcel bundling of script.js

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

We can get into cases where `startTime + periodDuration` causes initialization to fail (e.g. if someone's lazy and uses `MAX_UINT64` as `periodDuration`).
This just sets `endTime = max(startTime + periodDuration, MAX_UINT64)`.

Finance: handle endTime overflow for transitioning periods

---

apps/finance/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json
templates/beta/package.json

> truffle console should be truffle dev
I think truffle updated this a while back (probably on version 4) so that `truffle dev` is the standalone console.

Use truffle dev instead of truffle console

---

apps/token-manager/contracts/TokenManager.sol
apps/token-manager/test/tokenmanager.js

@izqui not sure if this was an oversight or if there was a reason this wasn't originally included?
Fixes:
> when revoking a vesting, there is no way to see historical data. adding _cliff, _start, etc to NewVesting. Also adding amount to RevokeVesting

TokenManager: allow clients to get more vesting details

---

apps/token-manager/contracts/TokenManager.sol
apps/token-manager/test/tokenmanager.js

See https://github.com/aragon/aragon-apps/pull/280#issuecomment-383041298.
~Adds a check to make sure the TokenManager is initialized to be non-transferable if the underlying minime token is also non-transferable.~
~I didn't force equality because the converse is less strict—even if the token was originally transferable, initializing the TokenManager as non-transferable would effectively make the token also non-transferable.~
~Fixes~
> ~check token.transfersEnabled on init~

TokenManager: let Minime token handle transferable-ness

---

templates/beta/docker-compose.yml

This way we can access it from outside and use it with the local apps
generated with aragon-dev-cli.

Templates: Expose IPFS 8080 port

---

apps/finance/contracts/Finance.sol
apps/token-manager/contracts/TokenManager.sol
apps/vault/contracts/Vault.sol
apps/voting/contracts/Voting.sol

Add isInitialized to all state-changing public functions

---

apps/finance/test/finance.js

With changes in PR #307 (commit bb6a18d8) sending would revert instead
of failing with invalid opcode, so last test needed to change from
`assertInvalidOpcode` to `assertRevert`. We didn't realize because CI was
broken prior to PR #309.

Finance: fix test

---

apps/finance/contracts/Finance.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

Is there a reason they're imported?
Vault's is removed in https://github.com/aragon/aragon-apps/pull/304.

Remove migrations import in app contracts

---

apps/finance/contracts/Finance.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

This reverts commit 4135078a2497cc807009b92069b8d5a7046b8b0e.
Missing migration contracts break the tests. Will be done later with https://github.com/aragon/aragon-apps/pull/318.

Revert "Remove migrations import in app contracts (#305)"

---

apps/voting/contracts/Voting.sol

Throughout the file, "Yea" is used as the spelling, which accurately aligns with the way it is spelled in US politics https://www.senate.gov/general/Features/votes.htm ,  so it should be 'yea' here instead of 'yay'

Change vote function comment to 'yea' from 'yay'

---

apps/survey/package.json

Required for dao-kits to install properly.
We can publish 1.0.0 when we merge the frontend.

Publish survey@0.0.1

---

apps/finance/package-lock.json
apps/survey/package-lock.json
apps/token-manager/package-lock.json
apps/voting/package-lock.json
apps/voting/package.json
package-lock.json
package.json

solium has a deep dependency on hoek@2.16.3 in voting app, token-manager app, vault app, we will have to wait for a version of solium without these deep dependencies to remove (or update to 4.2.1)  in these apps
Updating solium and eth-gas-reporter does not remove or update the hoek dependency to a newer version.
No hoek dependencies in finance app or survey app
Updating coveralls@2.13.3 to coveralls@latest to remove dependency on hoek in root project
Removed 1 high and 6 moderate vulnerabilities in root project
The ticket (#323) specifically stated hoek, but I can remove some other insecure dependencies with this commit if asked :)
Cheers

Updating coveralls in root project, removing hoek dependency (#323)

---

templates/beta/package.json

`npm install`ing in the root would fail because the beta template's `prepublish` script would run and fail.

Beta Template: prepublish => prepublishOnly

---

apps/survey/contracts/Survey.sol

Just realized that if someone directly invokes `resetVote()`, we'd never be able to know about it because there's no events.
This does cause `voteOptions()` to emit some, strictly speaking, unnecessary events (`CastVote` will be emitted immediately after), but I think this is better than hiding them; otherwise, from an event stream, it might look like that person is always adding more and more votes on each vote rather than resetting them each time.

Survey: add event when votes are reset

---

apps/finance/app/package-lock.json
apps/finance/app/package.json
apps/token-manager/app/package.json
apps/voting/app/package.json

Upgrading should allow us to avoid weird issues where web3.js was passing events back to the error handler rather than event handler.

Upgrade @aragon/client to 1.0.0-beta.8

---

apps/survey/contracts/Survey.sol

Makes it much, much easier on the frontend to calculate historical information about how an option was voted in a survey.
The voter's stake can still be found either by looking at the contract (if it hasn't been changed), or by looking at the events between two voting events.

Survey: emit current option's power

---

apps/voting/app/src/App.js

Fixes a propTypes error, because `title` is required.
AFAIK, this doesn't affect the `SidePanel`'s rendering and transitioning.

Voting: don't render SidePanel unless there's a vote to display

---

package.json

See https://git-scm.com/docs/git-clean.
Running `npm run clean` now cleans all git ignored files (before `lerna clean` wouldn't remove the nested `app/node_modules` inside each app's folder), interactively, to restore the repo to a pristine state (for, e.g. rebuilding all `package-lock.json`s).

Use git clean instead of lerna clean

---

package.json

The root package isn't meant to be published since it's a monorepo.

Make root package.json private

---

apps/survey/app/package.json
apps/survey/app/src/components/Survey/Survey.js
apps/survey/app/src/components/Survey/VotesCast.js
apps/survey/app/src/components/SurveyOptions/SurveyOption.js
apps/survey/app/src/components/SurveyOptions/SurveyOptions.js
apps/survey/app/src/components/Surveys/Surveys.js

- Upgrade `@aragon/ui` to 0.16.0 (fast `SidePanel` animation ✨).
- Upgrade `react-spring` to 5.4.0.
- Fix animation issues on Chrome 👌👌👌 (`translate3d()` / `scale3d()` all the things <img src="https://user-images.githubusercontent.com/36158/42833990-a03da570-89ed-11e8-99ff-a71615b1b005.png" width=20>).
- SurveyOptions: use the react-spring `delay` prop instead of `setTimeout()`.
- Surveys: use `React.PureComponent`.
- Tweak animation delays.
- `SurveyOptions`: prevent useless updates.
- Use the react-spring `delay` prop instead of `setTimeout()`.

Survey tweaks

---

apps/finance/contracts/Finance.sol

Uses the `ERC20` type when it's immediately casted to, anyway.
Solidity's type system will automatically downgrade contract types to `address` when necessary as well.

Finance: use ERC20 typing in function parameters

---

apps/finance/contracts/Finance.sol
apps/survey/contracts/Survey.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

Explicitly set the state to be `internal`, since these either have custom getters or have indices start at `1`.

Explicitly define state visibility

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

Also fixes the issue where the wrong, outdated budget can be passed to `CHANGE_BUDGETS_ROLE`. From https://github.com/ConsenSys/aragon-apps-audit-repo/issues/41:
> However, the settings.budget[_token] value should not be read without first checking settings.hasBudget[_token] because removeBudget keeps the old, invalid settings.budget[_token] value even though the limit is removed.

Finance: set the budget to 0 when removing a budget

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js
apps/finance/test/mocks/FinanceMock.sol

From https://github.com/ConsenSys/aragon-apps-audit-repo/issues/29:
> Remove the MAX_PERIOD_TRANSITION_PER_TX. Items 1 and 2 above together should make this arbitrary cutoff unnecessary.
--------------
If there are too many periods to transition, an OOG error will revert all changed state, including in-flight transfers of ETH or tokens.
However, this does mean the frontend may have a harder time estimating gas costs.

Finance: remove limit on transitions per transaction in transitionsPeriod modifier

---

apps/survey/test/mocks/BadToken.sol

Using static contract types instead of adddresses for MiniMe.
See https://github.com/aragon/aragonOS/pull/357

Survey: adapt mock test token to aragonOS PR 357

---

apps/finance/app/src/components/BalanceToken.js
apps/finance/app/src/components/Balances.js

Otherwise we always make a request to `https://chasing-coins.com/coin/logo/%C2%A0` unnecessarily.

Finance: fix unnecessary request to get token logo when loading placeholder

---

apps/finance/package.json

solidity-coverage@0.3.5 depends on a different version of webpack (3.12.0) rather than what react-scripts wants (3.10.0).

Finance: upgrade solidity-coverage to 0.4.3

---

apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json

This allows `apm publish` to build the frontend of the apps so just one command is required.
In case of the vault app that doesn't have a frontend, we just create the directory to avoid the issue of trying to publish an inexistent directory.

Add build command to main app repos

---

apps/finance/contracts/test/TestImports.sol
apps/finance/package.json
apps/survey/.solcover.js
apps/survey/contracts/Survey.sol
apps/survey/contracts/test/TestImports.sol
apps/survey/contracts/test/mocks/BadToken.sol
apps/survey/package.json
apps/token-manager/.solcover.js
apps/token-manager/contracts/TokenManager.sol
apps/token-manager/contracts/test/TestImports.sol
apps/token-manager/package.json
apps/vault/contracts/test/TestImports.sol
apps/vault/package.json
apps/voting/.solcover.js
apps/voting/contracts/Voting.sol
apps/voting/contracts/test/TestImports.sol
apps/voting/package.json
apps/voting/test/voting.js
package.json
shared/migrations/package.json
shared/minime/contracts/test/TestImport.sol
shared/minime/package.json

Moves the internal packages to be scoped as `@aragon/apps-shared-*` so they can be published.
Both are now published: [minime](https://www.npmjs.com/package/@aragon/apps-shared-minime), [migrations](https://www.npmjs.com/package/@aragon/apps-shared-migrations).

Publish internal packages

---

.travis.yml

An experiment to see if this makes our CI faster, as a significant part of each build is spent on npm installing.

chore: add more cache paths to travis

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Snapshot it for each vote, create role for it and add tests.
Needed for #270

Voting: Allow to modify required support

---

apps/voting/app/package.json

Until we upgrade the app to support the newer versions.

Pin parcel-bundler and date-fns to prevent any break

---

apps/voting/contracts/Voting.sol

In the case of > 1 forwarding steps before the Voting app is reached (e.g. allowing only token holders to create votes), it's impossible for the voting app to automatically vote on behalf of the end user who started the transaction right now.
This adjusts the radspec text to give us some leeway in the messaging around this case.

Voting: tweak forwarding action's radspec to be more clear that a vote is not always casted

---

apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/Panels/AssignVotePanelContent.js
apps/token-manager/app/src/utils.js
apps/token-manager/app/src/utils.test.js

Builds on #480 and #485.
Introduces `fromDecimals()` and `toDecimals()` utilities to translate between a string number and a token decimal base (very, very similar to `toWei()` and `fromWei()`).
Fixes the input field not having a step, and the accuracy of the conversion (`parseFloat()` would be inaccurate on large decimal bases).

Token Manager: fix input fields' step behavour and accuracy

---

apps/vault/contracts/Vault.sol
apps/vault/test/mocks/DestinationMock.sol
apps/vault/test/vault.js

Vault: remove ability to call contracts with data

---

apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

😅 Not sure how we've missed this for so long.
Without checking that the token has a total supply, you could create locked votes. We already have this check in the Survey app.

Voting: require votes to have positive token snapshots

---

apps/finance/arapp.json
apps/finance/artifact.json
apps/finance/contracts/Finance.sol
apps/finance/test/finance.js
apps/survey/contracts/test/mocks/BadToken.sol
shared/minime/contracts/MiniMeToken.sol

Also changes constant to view app-wide and renamed app-wide from disabled to inactive for the payment status.
#374

Rename setPaymentDisabled to setPaymentStatus

---

apps/voting/app/.eslintrc
apps/voting/app/src/App.js
apps/voting/app/src/components/SummaryRows.js
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/components/VoteStatus.js
apps/voting/app/src/components/VoteSuccess.js
apps/voting/app/src/components/VoteSummary.js
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/math-utils.js
apps/voting/app/src/screens/Votes.js
apps/voting/app/src/script.js
apps/voting/app/src/utils/provideSettings.js
apps/voting/app/src/vote-settings.js
apps/voting/app/src/vote-utils.js

Depends on #483.
Refactors the internal state model of the app.
Main changes:
- Moved most of the vote data structure manipulation into the `observe` block, as they don't need to be done on each render, and this helps ensure type purity as it's the "entry point" for data
- Moved everything related to a vote's contract state into `vote.data`
- Added a settings context provider (old API) for cases where we need some of the voting app's settings
- Except for time-based values, avoid passing back numbers from the script (prefer strings)
- Add `numData` fields to both the settings and each vote, for calculations that don't require accurate operations
- Use exact calculations when they're safer (e.g. when mimicking [`canExecute()`](https://github.com/aragon/aragon-apps/blob/master/apps/voting/co …

Voting: refactor state and better enforce bignumber purity

---

apps/finance/app/package.json
apps/token-manager/app/package.json
apps/voting/app/package.json

Didn't update survey as it is pinned to `0.16.0`.

Bump aragon-ui to 0.21.0

---

apps/finance/app/package.json
apps/finance/app/src/components/TransferRow.js
apps/finance/app/src/components/Transfers.js
apps/survey/app/package.json
apps/survey/app/src/components/SurveyCard/SurveyCard.js
apps/voting/app/package.json
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/vote-utils.js

Fixes the datetime formatting and pins `date-fns` to `@2.0.0-beta.22` so we don't get more unexpected surprises :).
See https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#changed-8 for the new format tokens and https://date-fns.org/v2.0.0-alpha.22/docs/Unicode-Tokens for popularly confused unicode tokens.

Fix date format

---

.travis.yml

AFAIK we only needed it for the dao-kits, which have since been moved.

chore: remove docker from travis CI

---

apps/token-manager/app/src/App.js

Fixes the empty state action button opening up the panel with '[Object object]' because it passes the event object 😅

Token Manager: fix empty state action

---

apps/survey/app/src/App.js
apps/survey/app/src/script.js

Discovered while debugging Memefactory's survey DAO. I didn't factor in resetting votes earlier when doing calculations for the history chart.
Also adds `logIndex` as a way to make sure we don't work on the same event.
**Breaking change**: all past survey DAOs use `0` to signify sparseness in their history whereas `-1` is now used (so we can properly account for when a vote is reset back to 0). Although the data model has changed, almost no users on mainnet should be impacted by this change, at least visually.
Before:
After:

Survey: fix calculation when votes are reset

---

apps/survey/test/survey.js
apps/voting/app/src/App.js
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/components/VotingCard/VotingOptions.js
apps/voting/app/src/screens/Votes.js
apps/voting/app/src/script.js
apps/voting/app/src/vote-utils.js
apps/voting/contracts/Voting.sol
apps/voting/test/voting.js

Aligns the terminology used between the Voting and Survey apps.
`votingPower` is a lot more clear than `totalVoters`, as `totalVoters` implies the number of people who voted.
**BREAKING CHANGE** for the voting app's frontend.

Rename totalVoters => votingPower

---

apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/voting/package.json

The `rc.1` builds are broken as well, because we don't publish the `app/` directory anymore.

chore: use prepare script instead of postinstall to avoid installing app dependencies in dependents

---

.travis.yml

Until https://github.com/sc-forks/solidity-coverage/issues/283 is fixed, the finance app requires a ridiculous amount of time to instrument its dependencies during coverage testing and usually causes the travis build to fail by hitting the max build time (50min).
Not the nicest, but it's a coverage test and there's not much else we can do for now aside from fixing solidity-coverage.

chore: allow coverage test for finance app to fail due to excessive timeouts

---

apps/finance/contracts/Finance.sol

From https://github.com/ConsenSys/aragon-apps-audit-repo/issues/45:
-----------------------------
Transitioning periods is only necessary when an action is related to the accounting periods, and these periods can be affected by any of the following:
- A transfer (in or out of the Finance app)
- Changing the period duration
- Changing the budget (since it's effective immediately, it should transition periods to only impact the relevant period if the app's behind)
Disabling or enabling a payment doesn't directly impact any of the above. I think an argument could be made either way, but I believe not having the modifier is safer, as it makes this management related functionality easier than pulling funds out (although this can also be argued in the reverse if the manager is malicious).

Finance: explain why setPaymentStatus() doesn't transition periods

---

apps/finance/app/src/abi/vault-balance.json
apps/finance/app/src/abi/vault-events.json
apps/finance/app/src/script.js

🙈 Way way back I must not have realized I forgot to include the Vault's events in the ABI we pass to `app.external()`. This adds the relevant ABI and allows the Finance app's script to properly react based on changes to the Vault (mostly important if deposits or transfers happen without the Finance app knowing about it).

Finance: fix vault ABI so events from the vault can be processed properly

---

apps/token-manager/app/src/components/SideBar.js
apps/token-manager/app/src/components/TokenBadge.js

Token manager: fix the token badge when the label is too long

---

apps/vault/contracts/Vault.sol

To prevent the Vault from being identified as an ERC20, causing fun things like this:

Vault: rename events to avoid clashing with ERC20 Transfer event

---

apps/finance/app/src/components/NewTransfer/TokenSelector.js
apps/finance/app/src/components/NewTransfer/Withdrawal.js

Fixes https://github.com/aragon/aragon/issues/508, adding asterisks to these panels:
-----
-----
------
Also makes the label unselectable in cases where we used a custom label.

Finance: add asterisks to all required input fields

---

apps/finance/app/src/abi/vault-getinitializationblock.json
apps/finance/app/src/script.js

Use the vault's own initialization block as the `fromBlock` when subscribing to vault events.

Finance: use attached Vault's initialization block as starting block for events

---

apps/finance/app/src/App.js
apps/finance/app/src/components/MenuButton/IconMenu.js
apps/finance/app/src/components/MenuButton/MenuButton.js
apps/finance/app/src/index.js
apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/MenuButton/IconMenu.js
apps/token-manager/app/src/components/MenuButton/MenuButton.js
apps/token-manager/app/src/index.js
apps/voting/app/src/App.js
apps/voting/app/src/components/MenuButton/IconMenu.js
apps/voting/app/src/components/MenuButton/MenuButton.js
apps/voting/app/src/index.js

These changes for the `Voting`, `Token Manager` and `Finance` apps add the mechanism to open/close the `MenuPanel` as shown [here](https://github.com/aragon/aragon/pull/539)

Responsive menu panel for iframe apps

---

apps/voting/app/src/App.js
apps/voting/app/src/components/NewVoteButton/NewVoteButton.js
apps/voting/app/src/components/VotePanelContent.js
apps/voting/app/src/components/VotingCard/VotingCardGroup.js

Responsive voting app

---

apps/voting/contracts/Voting.sol
apps/voting/contracts/test/mocks/VotingMock.sol
apps/voting/package.json
apps/voting/test/voting.js

Testing this is a bit contrived, but it does fail the previous contract version.

Voting: fix snapshot block for new vote

---

future-apps/actor/contracts/Actor.sol

I think this is important for a few reasons
1. It will make the Aragon Keyring simpler
2. Preventing execute from just sending eth doesn't add any security - functions can be created to sidestep this. It also might provide a false sense of security.
3. The validation costs gas

Agent: Allow execute to send Eth

---

apps/survey/app/src/script.js
apps/survey/contracts/Survey.sol

Makes it easier for frontends to correctly respond to votes being reset (if they're trying to correctly reflect the options' powers) and the previous value is always known from `previousStake + currentPower`.

 Survey: emit current option power on ResetVote events instead of previous option powers

---

apps/survey/contracts/Survey.sol

Oops, looks like these return values were mistaken to be input params.

Survey: fix named returns from getSurvey()

---

apps/voting/app/package.json
apps/voting/app/src/components/VotePanelContent.js

`react-blockies` isn't used anymore since it's been replaced by the `IdentityBadge`, and this also removes some dead code.

Voting: remove react-blockies

---

apps/token-manager/app/src/screens/EmptyState.js
apps/voting/app/src/screens/EmptyState.js

Fixes #660.
Updated the empty state card for the Token Manager with more descriptive terminology as suggested in #660.

(Token Manager) more descriptive empty card state for token manager

---

apps/voting/app/src/screens/EmptyState.js

Fixes #245.
Updated the empty state card for the voting App with more descriptive terminology as suggested in #245.
Will update the other Apps accordingly, once this one is approved.

(Voting) more descriptive empty state card

---

apps/survey/app/src/App.js
apps/survey/app/src/components/VotingPanel/VotingPanel.js
apps/survey/app/src/provide-network.js
apps/survey/app/src/utils.js

Addresses some comments in #677.
Also removes `etherscanBaseUrl`-related code, since it's not being used and it's now provided by aragonUI's `blockExplorerUrl()`.

Survey: PR comments

---

apps/survey/app/src/script.js
apps/survey/contracts/Survey.sol

Fixes compiler warning from https://github.com/aragon/aragon-apps/pull/680/files#r257791103.

Survey: avoid shadowing minParticipationPct in getSurvey()

---

apps/survey/contracts/Survey.sol

Looks like this change was reverted in https://github.com/aragon/aragon-apps/pull/473 by accident.
Although using `uint64` is a _little_ bit more expensive (applies a `uint64` mask on the value each time it's used), it's safer to use since the compiler will complain if we accidentally change this value and set a value that's too big.

Survey: change PCT_BASE to uint64

---

apps/agent/contracts/Agent.sol
apps/agent/test/agent.js

Found during security review. See https://github.com/aragon/aragon-apps/pull/611#discussion_r
The `signature` ACL parameter for the `EXECUTE_ROLE` contains a memory pointer rather than the actual value. The ACL param shouldn't be trusted until the Agent instance has been upgraded to a version with this patch.
Pending tests.

Agent: fix execute signature ACL param

---

apps/finance/app/src/App.js
apps/token-manager/app/src/App.js
apps/voting/app/src/App.js

cc @bpierre should we just make [`Main` default to using relative paths](https://github.com/aragon/aragon-ui/blob/master/src/components/Main/Main.js#L28)? (From @2color).

fix: update usage of @aragon'ui's Main component to use relative asset paths

---

apps/finance/app/package.json

Seems like we missed removing this when we moved everything to `react-springs`.

Finance: remove react-motion dependency

---

apps/agent/contracts/SignatureValidator.sol

Issue raised by ANSP in https://github.com/aragon/aragon-apps/pull/611#discussion_r261743914
- We were always copying one extra garbage byte (the full length of the input bytes array) when copying to the output array. Tested in all of the combined ERC1271 -> EthSign and ERC712 tests.
- Also avoid copying altogether in case that the input array only has one byte. Tested in the standalone ERC1271 tests

Agent: fix copying an extra byte in popFirstByte

---

apps/finance/contracts/Finance.sol
apps/survey/contracts/Survey.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

From https://github.com/aragon/aragon-apps/pull/611#issuecomment-465090647:
> * (info) - voting.sol - access modifiers - consider declaring functions external (optimization)
> * (info) - survey.sol - access modifiers - consider declaring functions external (optimization)
---------
This has mostly cosmetic changes, to make the function grouping based on visibility more clear to reviewers and readers of the code.
The main changes to the contracts are:
- 08420fd: Changes `isForwarder()` to external, now that the interface is declared with `external`
- c46151e: Changes a few public functions in Finance to be external, since they either had internal variants subclasses could use or should not be used by subclasses
- 6ccfaa0: Modernizes the authentication strategy in Survey, to one where only …

Finance, Token Manager, Survey, Voting: fix function-visibility

---

apps/finance/app/package.json
apps/finance/app/src/App.js
apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/index.js
apps/finance/app/src/lib/token-utils.js
apps/finance/app/src/rxjs.js
apps/finance/app/src/script.js

- Add `rxjs` as a dependency
- Improve dev experience by watching the script in dev/watch mode too
- Make code changes where necessary

Upgrade rxjs to v6 in finance app

---

apps/token-manager/app/package.json
apps/token-manager/app/src/components/HolderRow.js
apps/token-manager/app/src/components/SideBar.js
apps/token-manager/app/src/components/You.js
apps/token-manager/app/src/screens/Holders.js

Changes:
- Layout fixes to remove the horizontal scrollbar on small viewports (320px).
- Fix the spacing between the “You” badge and the Identity badge.
- Add the “You” badge in the sidebar.
- Upgrade `@aragon/ui` to `0.32.0`.
- IdentityBadge: always shorten + set the `connectedAccount` prop.
- Table: use the `noSideBorders` prop.

Token manager fixes

---

apps/finance/app/src/components/CustomLabelIdentityBadge/CustomLabelIdentityBadge.js
apps/finance/app/src/components/CustomLabelModal/CustomLabelModalManager.js

These changes make it possible to re-render extended `IdentityBadge`s for the same address when one updates its custom label:

Custom labels local observable

---

apps/token-manager/app/package.json
apps/token-manager/app/src/App.js
apps/token-manager/app/src/index.js
apps/token-manager/app/src/rxjs.js
apps/token-manager/app/src/script.js

- Add `rxjs` as a dependency
- Improve dev experience by watching the script in dev/watch mode too
- Make rxjs v6 code changes where necessary 
This PR is in the same vein as https://github.com/aragon/aragon-apps/pull/698

Upgrade rxjs to v6 in token-manager app 

---

apps/survey/contracts/Survey.sol

Optimizes `_voteOption()` by caching the `MultiOptionVote` storage variable, rather than recalculating its position multiple times.

Survey: optimize voteOption()

---

apps/finance/contracts/Finance.sol

Although not strictly necessary, we use these casts in other places where we convert from a non-uint256 type to be a parameter in `authP()`.

Finance: add uint256 casts for parameters in authP

---

apps/token-manager/contracts/TokenManager.sol

Seems like we forgot to remove this earlier. Shouldn't cause an issue with any upgrades since we weren't using the storage anyway.

Token Manager: remove unused storage mapping

---

apps/finance/contracts/Finance.sol

The event is actually being [emitted with whether the payment is active or not](https://github.com/aragon/aragon-apps/blob/master/apps/finance/contracts/Finance.sol#L351).
This is a breaking change for frontend clients relying on this parameter name, but to my knowledge nobody is using this parameter.

Finance: fix naming of status parameter in ChangePaymentState event

---

apps/voting/app/src/math-utils.js
apps/voting/app/src/script.js

Defaults the token decimals to 0 ("safest" assumption) if the token contract doesn't provide them.
In some cases, this can make the values look quite odd (if they're in the yuge range), and this includes a bit of logic to handle these exponents.
We'll leave the decimal matching as something to tackle with https://github.com/aragon/aragon/issues/589.
Numbers in sci. notation:

Voting: default decimals to 0 if token contract doesn't specify them

---

apps/finance/contracts/Finance.sol
apps/token-manager/contracts/TokenManager.sol
apps/vault/contracts/Vault.sol

See https://github.com/aragon/aragon-apps/pull/611#discussion_r266643982.

Finance, Token Manager, Vault: use address(this) for address arguments

---

apps/finance/contracts/Finance.sol

See https://github.com/aragon/aragon-apps/pull/611#discussion_r266640876.
Periods are numbered as `uint64`s, so it will never make sense to transition more. Related external methods for transitioning periods already use `uint64`.

Finance: _tryTransitionAccountPeriod should take uint64 argument

---

future-apps/payroll/contracts/Payroll.sol

cc @lmcorbalan @bingen 
Changes the `employeeExists` modifier to instead check if an employee is still active (their end date hasn't been reached).
This allows the app to:
- Remove the `terminated` storage for each employee, as invoking `terminateEmployeeNow()` twice in the same block will fail (employee is only active if their end date hasn't been reached)
- Change details about a yet-to-be "terminated" employee (one who has an non-MAX_UINT64 end date but whose end date has not been reached), such as salary, their actual end date, etc.
Note that this does allow you to "terminate" an employee multiple times, if you set their end date in the future. I'd argue this is a terminology problem though (see below).
----------
Further potential changes:
- We could change the terminology around …

[WIP] Payroll: remove terminated storage and change exist modifier for activeness check

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/package.json
future-apps/payroll/test/payroll_allowed_tokens.js
future-apps/payroll/test/payroll_gascosts.js

**MERGE AFTER https://github.com/aragon/aragon-apps/pull/729**
The [test](https://github.com/aragon/aragon-apps/blob/4ae5f2fe558271fc4aa329248b23936d76bcc6d7/future-apps/payroll/test/payroll_allowed_tokens.js#L85-L93) that was trying to ensure that the payroll contract could handle up to 25 tokens was failing. The Finance contract was running out of gas when trying to perform the last transfer.
I added some tests to check how much increases the payout process of the Payroll contract for each new allowed token, which is [~260k](https://github.com/aragon/aragon-apps/commit/4ae5f2fe558271fc4aa329248b23936d76bcc6d7#diff-9335e65fae396b052e4ee57474e4b3c3R82). Having in mind that performing a transaction for a single allowed token costs …

Payroll: Fix max allowed tokens length

---

apps/voting/contracts/test/mocks/VotingMock.sol
apps/voting/test/voting.js

Must've forgot to do this back when we migrated to aragonOS@4 😅. `timeTravel()` isn't supported outside of Ganache, so we generally use the built-in time mocks in `AragonApp`.

Voting: mock time in tests rather than use timetravel

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js
apps/survey/contracts/Survey.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

Builds on https://github.com/aragon/aragon-apps/pull/702.
An attempt at an answer to https://github.com/aragon/aragon-apps/pull/686#discussion_r259411928.
This will be added as a guideline to hack.aragon.org (soon), but in short, my current thoughts on where to place security modifiers in Aragon apps:
- "Lowest" in the call stack:
- Place internal state assertions as close as possible to where they're required or used
- Place external call assertions as close as possible to where the call happened
- "Highest" in the call stack:
- Place authentication assertions as close as possible to the start of the externally accessible function
- Place parameter assertions as close as possible to the start of the externally accessible function
- In places where an expensive state assertion will be …

Finance, Survey, Token Manager, Voting: Clarify internal protection scheme

---

apps/token-manager/contracts/TokenManager.sol
apps/token-manager/test/tokenmanager.js

This change adds more checks to disallow usage of the `mint()` and `assignVested()` actions for the Token Manager itself:
- `mint()`: you should use `issue()` instead (separate action protected by a separate role)
- `assignVested()`: Assigning vestings to the Token Manager makes the accounting awkward when calculating the spendable balance of the Token Manager itself. The Token Manager itself never has a spending limit (see `onTransfer()`, so the concept of a vesting does not work very well.
This change also modifies the way `_isBalanceIncreaseAllowed()` works, by always allowing increases to the Token Manager's balance.
Previously, using `assign()` with the Token Manager as the recipient would fail if its balance was already over the limit (see [previously failing …

 Token Manager: disallow minting and vesting tokens to itself

---

apps/token-manager/contracts/TokenManager.sol
apps/token-manager/contracts/test/mocks/TokenManagerMock.sol
apps/token-manager/test/tokenmanager.js

Builds on #734, but should be merged separately.
Similar to #737, we should use the built-in `TimeHelpers` and time mocking instead of relying on `now` and `timeTravel()`.

Token Manager: use TimeHelpers and mock time in tests

---

apps/finance/contracts/Finance.sol

- Amends the comments for it using `MAX_UINT` as its interval auth parameter
- Reorders it to be above `newScheduledPaymentI)`

Finance: cosmetic clarifications for newImmediatePayment()

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

Builds on #711, but should be merged separately.
Now that the function name is called `newScheduledPayment()`, I thought it might make sense to rename the struct to also be `ScheduledPayment`.

Finance: rename RecurringPayments to ScheduledPayments

---

apps/finance/contracts/Finance.sol
apps/finance/test/finance.js

Builds on #711, but should be merged separately.
Renames `maxRepeats` to `maxExecutions` to better reflect the parameter and state.
A `maxRepeats` of 1 is quite confusing as to whether it means you can repeat the payment once (e.g. actually execute it twice), or only execute it once.

Finance: rename maxRepeats to maxExecutions

---

apps/finance/contracts/test/mocks/FinanceMock.sol
apps/finance/test/finance.js

Fixes the mocked time in Finance's tests to be similar to #737 and #738.

Finance: fix usage of timestamp mock in tests

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/contracts/test/mocks/PayrollMock.sol
future-apps/payroll/test/payroll_accrued_value.js
shared/test-helpers/assertThrow.js

This PR revives what @bingen has been working on in order to avoid overflows while transferring the payroll + the accrued value ([see here](https://github.com/protofire/aragon-apps/pull/113)). However,  I'm proposing another alternative in order to deal with this edge case. The idea is to split the interface allowing the employees to request their salary or accrued value separately. 
Additionally, I used the verb `reimburse` to refer to the action of paying the accrued value to an employee, please let me know if there is a more suitable way to refer to it (cc @izqui @luisivan).

Payroll: Avoid payout overflow

---

future-apps/payroll/contracts/test/mocks/PayrollMock.sol
future-apps/payroll/contracts/test/mocks/PriceFeedMock.sol
future-apps/payroll/test/contracts/Payroll_forwarding.test.js
future-apps/payroll/test/contracts/Payroll_modify_employee.test.js
future-apps/payroll/test/contracts/Payroll_payday.test.js
future-apps/payroll/test/contracts/Payroll_reimbursements.test.js
future-apps/payroll/test/contracts/Payroll_terminate_employee.test.js
future-apps/payroll/test/contracts/Payroll_token_allocations.test.js
shared/test-helpers/contracts/TimeHelpersMock.sol

This PR improves timestamp mocking in a more consistent way and provides a new common mocking contract that can be easily re-used.

Payroll: Improve timestamps mocking

---

shared/test-helpers/ganache-cli.sh

Main idea was to avoid relying on `nc` in order to kill a process that is running on the port we want to use. Instead I'm adding adding a `cleanup` function with `trap` to ensure we always end the rpc process we have started. If there is a foreign process running on that port we shouldn't kill it, it's expected to fail rather than taking over a port while killing the process that is using it.
It may fix #775 since we are not relying on `nc` anymore.

Shared: Organize ganache cli script

---

apps/finance/contracts/Finance.sol

Makes these variables a little bit more clear and easy to search for.

Finance: rename MAX_UINT to MAX_UINT256

---

apps/finance/app/src/components/Balances.js

Oops, we weren't passing enough info down to `BalanceToken` 🙈

Finance: fix balances not displaying verified token logos

---

apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/HolderRow.js
apps/token-manager/app/src/components/Panels/AssignVotePanelContent.js
apps/token-manager/app/src/screens/EmptyState.js
apps/token-manager/app/src/screens/Holders.js

_Builds on https://github.com/aragon/aragon-apps/pull/764 (do not merge before)_
_Fixes https://github.com/aragon/aragon-apps/issues/509_
See also https://github.com/aragonone/product/issues/41#issuecomment-480219715

Token manager copy

---

apps/agent/test/agent.js
apps/finance/test/finance.js
apps/survey/test/survey.js
apps/vault/test/vault_shared.js
future-apps/payroll/contracts/Payroll.sol
shared/test-helpers/assertThrow.js
shared/test-helpers/utils.js

Builds on #739, but should be merged separately.
Cherry-picks the change by @facuspagnuolo in https://github.com/aragon/aragon-apps/pull/736/commits/6964450e3d56159fd8049d6a3c7a4a4bf2de79a1 (to place it in `next`) and builds off of it.
Found a few previously broken tests with the revert strings 😄.

Finance: test revert strings

---

apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/components/NewTransfer/PanelContent.js
apps/finance/app/src/components/NewTransfer/Withdrawal.js
apps/token-manager/app/src/components/Panels/AssignVotePanelContent.js

Uses `createRef()` and adds a few enhancements to Finance's panels:
- Avoid flickering when closing the panel
- Reset the panel's state, so re-opening the deposit or withdraw after sending a transaction doesn't display the same information
- Auto focus the withdraw address panel
- Display a better message when the user has no tokens to deposit
Not super nice, but good enough for now 😄.

Finance, Token Manager: fix panels

---

.travis.yml

Looks like the store cache was timing out with the default of 3min.

chore: increase travis cache timeout

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/package.json
future-apps/payroll/test/contracts/Payroll_modify_employee.test.js

Accrued salary was being capped to max int if it there was an overflow. I'm splitting the way we calculate owed salary in order to:
- Revert in case the employer tries to set a new salary when the owed salary amount could not be represented as accrued salary due to an overflow
- Rescue capping to max int in case we are computing a payroll payment to allow employees withdrawing at least a portion of their owed salary
The rest of the scenarios (reimbursements and bonuses) will never overflow since those additions are being calculated with `SafeMath`.

Payroll: Fix accrued salary calculation

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/contracts/test/mocks/PriceFeedMock.sol
future-apps/payroll/package.json
future-apps/payroll/test/contracts/Payroll_add_employee.test.js
future-apps/payroll/test/contracts/Payroll_allowed_tokens.test.js
future-apps/payroll/test/contracts/Payroll_bonuses.test.js
future-apps/payroll/test/contracts/Payroll_forwarding.test.js
future-apps/payroll/test/contracts/Payroll_gas_costs.test.js
future-apps/payroll/test/contracts/Payroll_get_employee.test.js
future-apps/payroll/test/contracts/Payroll_initialize.test.js
future-apps/payroll/test/contracts/Payroll_modify_employee.test.js
future-apps/payroll/test/contracts/Payroll_payday.test.js
future-apps/payroll/test/contracts/Payroll_reimbursements.test.js
future-apps/payroll/test/contracts/Payroll_settings.test.js
future-apps/payroll/test/contracts/Payroll_terminate_employee.test.js
future-apps/payroll/test/contracts/Payroll_token_allocations.test.js
future-apps/payroll/test/helpers/deploy.js
future-apps/payroll/test/helpers/set_token_rates.js
shared/test-helpers/assertThrow.js

Fixes #792 
Tests won't pass until we have a new version of PPF released including  https://github.com/aragon/ppf/pull/19, https://github.com/aragon/ppf/pull/20, https://github.com/aragon/ppf/pull/21, https://github.com/aragon/ppf/pull/22, and https://github.com/aragon/ppf/pull/23 changes

Payroll: Fix exchange rates request call

---

apps/voting/app/src/components/NewVotePanelContent.js
apps/voting/app/src/components/VoteStatus.js
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/vote-utils.js

Fixes https://github.com/aragon/aragon-apps/issues/582 and https://github.com/aragon/aragon-apps/issues/732

Voting app: clarify polls

---

future-apps/payroll/README.md
future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/contracts/test/mocks/MaliciousEmployee.sol
future-apps/payroll/package.json
future-apps/payroll/test/contracts/Payroll_add_employee.test.js
future-apps/payroll/test/contracts/Payroll_bonuses.test.js
future-apps/payroll/test/contracts/Payroll_forwarding.test.js
future-apps/payroll/test/contracts/Payroll_gas_costs.test.js
future-apps/payroll/test/contracts/Payroll_get_employee.test.js
future-apps/payroll/test/contracts/Payroll_modify_employee.test.js
future-apps/payroll/test/contracts/Payroll_payday.test.js
future-apps/payroll/test/contracts/Payroll_reentrancy.test.js
future-apps/payroll/test/contracts/Payroll_reimbursements.test.js
future-apps/payroll/test/contracts/Payroll_terminate_employee.test.js
future-apps/payroll/test/contracts/Payroll_token_allocations.test.js

Fixes #759 
The CI failed because we reached the max size limit of a contract, I'm proposing to simplify the external interface removing some redundant functions. I'm dropping `addEmployeeNow` and `terminateEmployeeNow`, in favour of leaving simply `addEmployee` and `terminateEmployee`.

Payroll: Add reentrancy guard to payment transfers

---

apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/lib/token-utils.js
apps/finance/app/src/script.js

Fixes https://github.com/aragon/aragon/issues/734.
With https://github.com/aragon/aragon.js/pull/277 we now get the actual errors back from the RPC when a call goes wrong (e.g. naive `token.symbol()` on DAI) and we need to handle these explicitly.
This PR converts a lot of the token fallback-related bits into simpler Promise-based code and adds explicit handlers for their error cases.

Finance: fix token fallbacks and error handling

---

apps/agent/package.json
apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json

cc @facuspagnuolo 
Hopefully this will get travis to run a bit faster with a lighter cache. Might be some other cache improvements we can make... somehow the cache on travis is yuge at 16GB:

chore: remove unnecessary dependencies

---

apps/agent/test/agent_shared.js
apps/finance/test/finance.js
apps/survey/test/survey.js
apps/token-manager/test/tokenmanager.js
apps/vault/test/vault_shared.js
apps/voting/test/voting.js
shared/minime/test/minime.js

This PR carries some enhancements related to test files:
- Use new `assertRevert` promisified interface
- Remove unused imports and constants
- Declare magically assigned variables
- Improve injected accounts usage

Apps: Tests enhancements

---

apps/finance/app/src/components/DateRange/DatePicker.js
apps/finance/app/src/components/DateRange/DateRangeInput.js
apps/finance/app/src/components/Transfers.js
apps/finance/app/src/components/TransfersFilters.js

These changes:
- Placeholder for dates: `--/--/----`
- When no range is selected today's date is used as placeholder for `endDate`
- When `startDate` is selected but no `endDate`, then `endDate` uses the placeholder
- Date range filter is applied when the user clicks outside of the date range picker instead of when clicking on dates as before
- Modified today's border to main color
- Uses monospaced font so that placeholder uses same char width as actual dates and uses `ch` units to define container's size
Refs: #809 and https://github.com/aragon/aragon-apps/pull/767#discussion_r274326591

Finance: date filters remove default selection

---

apps/agent/package.json
apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json
future-apps/payroll/package.json
shared/test-helpers/package.json

Oops, `npx` doesn't like nested binaries 🤦‍♂️.
We have to manually make sure the binaries are installed, otherwise `npx` might not find them (e.g. `testrpc-sc`, which isn't a package by itself but is exposed by `solidity-coverage`). This was causing the CI to fail on the coverage tests.
Todo:

chore: fix solidity-coverage in apps

---

future-apps/payroll/contracts/Payroll.sol

This should avoid a few unnecessary `SLOAD`s that result to the same state.

feat(Payroll): small SLOAD optimizations to _transferTokensAmount()

---

apps/voting/app/src/screens/Votes.js

Votes can sometimes be created in the same block, and so will have the same start (and end time) attached.
In this case, we should use their `voteId`s for sorting, so that the vote numbers still look correct (as you would expect a "newer" vote, with a larger `voteId`, to have a later end date).

Voting: sort same end-time votes by their descending voteIds

---

apps/finance/app/src/lib/utils.js

Prevents the app to crash on the current Firefox Nightly.
I couldn’t find any other use of `toLocaleString()` in `aragon/aragon-apps` / `aragon/aragon` / `aragon/aragon-ui` / `aragon/aragon.js` / `aragon/apm.js` so it should be the only change needed.
Thanks to @dizzypaty for reporting this issue! :1st_place_medal:

Prevent RangeError when .toLocaleString() is used

---

shared/test-helpers/ganache-cli.sh

I was getting:
```
./node_modules/@aragon/test-helpers/ganache-cli.sh: 4: set: Illegal option -o pipefail
```
I supposed is not a portable option.

Fix ganache-cli.sh on Ubuntu

---

apps/voting/app/.babelrc
apps/voting/app/package.json
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/math-utils.js
apps/voting/app/src/math-utils.test.js

Ref: fixes https://github.com/aragon/aragon/issues/742
The error came from [this line](https://github.com/aragon/aragon-apps/blob/master/apps/voting/app/src/math-utils.js#L95): the check was not `break`ing because `(0.55 * 100 * 100) % 1  = 9.094947017729282e-13` (even though `(0.55 * (100 * 100)) % 1 = 0`).
Applied the function that is being used in the survey app and added local tests for voting.
As discussed with @bpierre we need to add a `shared/common` library for all the apps.

Fix voting displayed percent

---

apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js
apps/voting/app/src/components/NewVotePanel.js
apps/voting/app/src/components/VotePanel.js
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/screens/Votes.js
apps/voting/app/src/utils-hooks.js
apps/voting/app/src/vote-hooks.js

Noticeable improvement: the side panels transition should be smoother.
Changes:
- Move panels in their own components, so that the rendering of   SidePanel can be skipped entirely.
- Memoize the object returned by usePanel(), so that it can be compared   using a strict equality.
- Move the voting panel actions in their own component fetching their   data, so that the panel component doesn’t need to render that much   anymore.
- Don’t recreate `votes` every second, instead only do it if any   “opened” status has changed.

Voting: skip unnecessary renderings

---

apps/finance/app/package.json

Babel@7.4.0 is deprecating core-js@2 and `@babel/polyfill`, so it will by default try to select `core-js@3`.
Luckily for Finance, we had another module that used core-js@2 so we got the correct version. This introduces an explicit dependency for this until we want to upgrade to core-js@3 (unfortunately it produces a bigger bundle 😦)

Finance: explicitly include core-js@2

---

future-apps/payroll/contracts/Payroll.sol

🙈 Oops, forgot to remove this as part of https://github.com/aragon/aragon-apps/pull/834/commits/3eab68a8b10c25d936ebb6e74647f6daf0295c84.
It's not needed anymore, because we calculate the last payroll date based on the actual amount paid rather than short circuiting it to `now` if it's the same as the currently owed amount.

Payroll: remove unnecessary variable in internal method

---

apps/voting/app/package.json
apps/voting/app/src/components/VoteText.js

Requires the master branch of @aragon/ui.

Voting: use IdentityBadge on VotingCard

---

future-apps/payroll/.gitignore

Removes the `.gitignore` file in Payroll, which was redundant as everything it ignored was already listed in `aragon-apps/.gitignore`.
The `.gitignore` in `future-apps/payroll` was making the CLI ignore the built frontend.

Payroll: remove .gitignore

---

apps/finance/app/src/components/DateRange/DatePicker.js
apps/finance/app/src/components/DateRange/DateRangeInput.js

Reference: https://github.com/aragonone/product/issues/88
These changes:
**Screenshots:**
**How to test**:
```sh
REACT_APP_ASSET_BRIDGE=local npm run start
git checkout feature/ux-improvements-date-range-picker
npm i
npm start 
```
Open up browser to http://localhost:3000 and head to Finance app

UX improvements date range picker

---

apps/agent/test/agent_shared.js
apps/finance/test/finance.js
apps/survey/test/survey.js
apps/token-manager/test/tokenmanager.js
apps/vault/test/vault_shared.js
apps/voting/test/voting.js
future-apps/payroll/test/contracts/Payroll_add_employee.test.js
future-apps/payroll/test/contracts/Payroll_allowed_tokens.test.js
future-apps/payroll/test/contracts/Payroll_bonuses.test.js
future-apps/payroll/test/contracts/Payroll_forwarding.test.js
future-apps/payroll/test/contracts/Payroll_get_employee.test.js
future-apps/payroll/test/contracts/Payroll_modify_employee.test.js
future-apps/payroll/test/contracts/Payroll_payday.test.js
future-apps/payroll/test/contracts/Payroll_rates.test.js
future-apps/payroll/test/contracts/Payroll_reimbursements.test.js
future-apps/payroll/test/contracts/Payroll_settings.test.js
future-apps/payroll/test/contracts/Payroll_terminate_employee.test.js
future-apps/payroll/test/contracts/Payroll_token_allocations.test.js
future-apps/payroll/test/helpers/deploy.js
future-apps/payroll/test/helpers/events.js
shared/test-helpers/assertEvent.js
shared/test-helpers/events.js

Borrowing events helpers and assert methods from aragonOS to improve the way we are dealing with those in the apps tests, at least until we release a new version exporting those new libraries.

Tests: Enhance events assertions

---

.travis.yml

Refactors the Travis pipeline to be built in stages, so the longer-running coverage tasks only get kicked off after the tests pass.
It also moves the Finance app's coverage tests away from being expected to fail, because the coverage improvements in https://github.com/aragon/aragon-apps/pull/863 have made the instrumentation much, much faster.

Travis: optimizations and refactor to use build stages

---

apps/finance/app/src/App.js
apps/token-manager/app/src/App.js
apps/voting/app/src/app-logic.js

Breaking change from https://github.com/aragon/aragon.js/pull/305 (to be released as `@aragon/rpc-messenger@2`).
I believe intents were the only RPC requests we were sending without caring for their response. All other requests were either made for their response, or we wanted to have feedback if the user cancelled (e.g. identity modifications)

Apps: update for @aragon/rpc-messenger's new deferred behaviour

---

apps/finance/app/package.json
apps/finance/app/src/App.js
apps/finance/app/src/script.js

- Replace the `INITIALIZATION_TRIGGER` with an init function (part of the [new API](https://github.com/aragon/aragon.js/pull/297))
- Pass the external vault contract and its `initializationBlock` to the api to leverage caching
- Loading/Syncing indicator
- https://github.com/aragon/aragon.js/pull/297

Finance - use updated app API with caching and init

---

apps/finance/app/src/script.js
apps/token-manager/app/src/script.js
apps/voting/app/src/script.js

Tries to apply a consistent style across the WebWorker scripts.
I liked leaving the `return nextState` at the end previously, because it was easy to add debugging logs, but this is still fairly easy to do by piping a `tap()` operator.

Apps: use consistent style across WebWorker scripts

---

apps/voting/app/src/script.js

- Fix an an caught error which would crash the background script 
- The error was detected with the following `newVote` [tx](https://etherscan.io/tx/0x5dc24de292dcc6e4728b973629a4d3f1a9eb1a2954a851d054f4507e273c2c01)
- Render votes with invalid scripts with an error message
- https://mainnet.aragon.org/#/futhorcecosystem/0xd9ed670476974e371607c9a6f8bffd44462510af

voting: catch invalid script error

---

apps/voting/app/src/components/VotePanel.js
apps/voting/app/src/components/VotingCard/VotingCard.js
apps/voting/app/src/script.js

- `description` takes precedence over `metadata`
- Render description first
- Do not nullify metadata for invalid scripts
For `/#/futhorcecosystem/0xd9ed670476974e371607c9a6f8bffd44462510af` with an invalid vote:

Improve invalid script handling

---

apps/finance/app/src/components/Transfers.js

The commas from the formatted amount were breaking the csv, by wrapping with `"` this does not happen anymore.
Ref: https://github.com/aragon/aragon-apps/issues/893

Transfers: wrap amount to avoid csv parsing errors

---

apps/agent/package.json
apps/finance/package.json
apps/survey/package.json
apps/token-manager/package.json
apps/vault/package.json
apps/voting/package.json
future-apps/payroll/package.json
shared/minime/package.json
shared/test-helpers/package.json

With the changes in #864 (see [`assertEvent()`](https://github.com/aragon/aragon-apps/commit/102b85e6d986d2106ada9b0d81c6cd0ba051571b#diff-f72e32bf8d0e8ebb509795f5d9457118)), `test-helpers`'s external API has a breaking change from the last published version.

test-helpers: publish new major

---

apps/agent/contracts/Agent.sol

The parameters to the `@tokenAmount` helper were swapped which is causing the evaluation of the radspec string to error when the ETH amount is greater than 0

Fix Agent radspec string for execute

---

apps/agent/manifest.json
apps/token-manager/manifest.json
apps/vault/manifest.json
apps/voting/manifest.json

This commit pretends to remove "details_url" that seems duplicated from line 6 to me.
Was probably not harming too much, but IMHO is better to fix the duplication, does it make sense?

Delete duplicated "details_url" from manifest.json

---

future-apps/payroll/contracts/Payroll.sol

*Fixing finding 6.8 of audit report*
| Severity     | Status    | Remediation Comment |
|:------------:|:---------:| ------------------- |
| Minor | Open | This issue is currently under review. |
`Payroll` imports `SafeMath8` but it is never used.
**code/payroll/future-apps/payroll/contracts/Payroll.sol:L10**
```solidity
import "@aragon/os/contracts/lib/math/SafeMath8.sol";
```
Remove the unused import statement.

Payroll: Remove unused import

---

future-apps/payroll/.solcover.js
future-apps/payroll/contracts/examples/PayrollKit.sol

Simply to avoid confusing with a real kit, it is only used for testing purposes

Payroll: Move payroll example kit into `contracts/examples/` dir

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/test/contracts/Payroll_constants.test.js

*Fixing finding 6.9 of the audit report*
| Severity     | Status    | Remediation Comment |
|:------------:|:---------:| ------------------- |
| Minor | Open | This issue is currently under review. |
A slight gas optimization can be done to the `*_ROLE` constants. 
At the moment, the code is very readable because the constants are clearly specified and the developer and reviewer understand and trust the value computed is the correct one.
**code/payroll/future-apps/payroll/contracts/Payroll.sol:L23-L30**
```solidity
bytes32 constant public ADD_EMPLOYEE_ROLE = keccak256("ADD_EMPLOYEE_ROLE");
bytes32 constant public TERMINATE_EMPLOYEE_ROLE = keccak256("TERMINATE_EMPLOYEE_ROLE");
bytes32 constant public SET_EMPLOYEE_SALARY_ROLE = keccak256("SET_EMPLOYEE_SALARY_ROLE");
bytes32 constant public …
```

Payroll: Hardcode role constant values

---

future-apps/payroll/contracts/Payroll.sol

Inlines `_updateEmployeeLastPayrollDate()` and optimizes a bit of the math / SSTOREs.

Payroll: optimize current payday remainders

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/contracts/examples/PayrollKit.sol
future-apps/payroll/contracts/test/mocks/PriceFeedMock.sol
future-apps/payroll/package.json
future-apps/payroll/test/contracts/Payroll_gas_costs.test.js

*Fixing finding 6.6 of the audit report*
| Severity     | Status    | Remediation Comment |
|:------------:|:---------:| ------------------- |
| Minor | Open | This issue is currently under review. |
The decimal calculation is using a hardcoded `ONE = 10 ** 18`; in both PPF (**uint256**) and Payroll (**uint128**) contracts. 
- In `PPF.sol`:
**code/ppf-contracts/packages/ppf-contracts/contracts/PPF.sol:L11**
```solidity
uint256 constant public ONE = 10 ** 18; // 10^18 is considered 1 in the price feed to allow for decimal calculations
```
- In `Payroll.sol`:
**code/payroll/future-apps/payroll/contracts/Payroll.sol:L32**
```solidity
uint128 internal constant ONE = 10 ** 18; // 10^18 is considered 1 in the price feed to allow for decimal calculations
```
This can result in an issue in some …

Payroll: Use PPF rate precision

---

future-apps/payroll/contracts/Payroll.sol
future-apps/payroll/test/contracts/Payroll_payday.test.js

*Fixing finding 6.3 of the audit report*
| Severity     | Status    | Remediation Comment |
|:------------:|:---------:| ------------------- |
| Medium | Open | This issue is currently under review. |
An employee can lose up to a second of their salary on calling `payday` function. It happens if the employee requests a specific amount of money that cannot be formed by multiplying salary-per-second base-unit `denominationTokenSalary` and any amount of seconds. On that case, rounding is done in favour of an employer. 
**code/payroll/future-apps/payroll/contracts/Payroll.sol:L751-L759**
```solidity
uint256 timeDiff = _paidAmount.div(employee.denominationTokenSalary);
// We check if the division was perfect, and if not, take its ceiling to avoid giving away
// tiny amounts of salary.
// …
```

Payroll: Add payroll remainders as accrued salary

---

future-apps/payroll/contracts/Payroll.sol

Handles both the cases, where someone may:
- Request less than their salary per second
- Request a multiple (and then some) of their salary per second

Payroll: handle both cases of extra salary being sent to accrued balance

---

future-apps/payroll/test/contracts/Payroll_payday.test.js

Modified a few of the tests to try and cover the case we had with `payday()`'s extra remainder salary being moved into the employee's accrued salary.

Payroll: cover cases for moving extra pay from payday into accrued salary

---

future-apps/payroll/contracts/Payroll.sol

Payroll: optimize by passing employee around as storage pointer

---

.github/auto_assign.yml
.github/autolabeler.yml
.github/config.yml
.github/release-drafter.yml
.github/stale.yml

- Adds https://probot.github.io/apps/welcome to welcome people who open issues and PRs and congratulates them on their first PR getting merged
- Adds https://probot.github.io/apps/stale to remind people with issues opened for 6 months, and PRs opened for a month without activity. Closes if there's no reply for a week
- Adds https://probot.github.io/apps/release-drafter to automatically draft release notes by using commit history
- Adds https://probot.github.io/apps/auto-assign to auto-assign @sohkai and @bpierre reviewers for PRs

Added probot bots

---

.travis.yml

Moves this long-running (1h+) test into its own stage, so that it doesn't block the rest of the coverage tests from running.

Travis: move Payroll's payday() tests into its own integration test stage

---

CONTRIBUTING.md
README.md
scripts/install

Fixes #370.
Also adds few notes on the branching strategy, as well as some developing and contributing notes.

Add CONTRIBUTING.md and improve readme

---

apps/voting/arapp.json
apps/voting/contracts/Voting.sol
apps/voting/scripts/vote-stats.js
apps/voting/test/contracts/voting.js
apps/voting/test/contracts/voting_delegation.js
apps/voting/test/helpers/voting.js

Related to https://github.com/aragon/aragon/issues/590
This PR aims to turn the fact that votes can be early executed once they have already been decided, into a configurable option.

Voting: Make early execution configurable

---

apps/token-manager/contracts/TokenManager.sol

Fixes https://github.com/aragon/aragon-cli/issues/524 
Turns out it was simply a typo in the radspec of the `TokenManager` `initialize` function.

Fix TokenManager radspec typo

---

apps/finance/app/src/script.js
apps/token-manager/app/src/script.js
apps/voting/app/src/script.js

In cases where some `eth_call`s fail (when they shouldn't, because we received an event for the new state), add an exponential backoff for fetching the new state.
It should not be a huge problem to queue new events like this when we wait for the exponential backoff to finish; usually inconsistent nodes are not _so_ behind (they're usually only at most a block behind), and it's unlikely the queue will be overrun by new events.

Apps: add exponential backoff to eth_calls when they fail

---

apps/finance/app/now.json
apps/finance/app/package.json

Similar to #937, allows someone to deploy to `nightly-finance.aragon.org` with
```
now --target production
```
**Note**: It appears `@aragon/ui@1.0.0-alpha.7` is not including all the new components (e.g. `Layout` and `Header`) and so the build currently requires one to link from `aragon-ui`.

Finance: deploy preview to now

---

apps/voting/app/now.json
apps/voting/app/package.json

Similar to #937, allows someone to deploy to `nightly-voting.aragon.org` with
```
now --target production
```

Voting: deploy preview to now

---

apps/token-manager/app/now.json
apps/token-manager/app/package.json

Sets up a `now.json` file that allows someone to use
```
now --target production
```
to deploy a preview to `nightly-token-manager.aragon.org`.

Token Manager: deploy preview to now

---

apps/agent/arapp.json
apps/agent/contracts/Agent.sol
apps/agent/contracts/test/mocks/ExecutionTarget.sol
apps/agent/test/agent_shared.js

Fixes https://github.com/aragon/aragon-apps/issues/656.

Merge Pool into Agent

---

apps/voting/app/src/script.js

Fixes some errors in the script if the user's account wasn't connected.

Voting: don't query vote status when there's no connected account

---

.gitignore
apps/voting/app/src/abi/token-balanceOf.json

Avoid selecting /build and /abi folders too deep into the repo, so that app frontends can control this themselves.

chore: fix gitignore

---

apps/finance/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/components/Transfers.js
apps/finance/app/src/lib/web3-utils.js
apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/InfoBoxes.js
apps/token-manager/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/token-manager/app/src/screens/Holders.js
apps/voting/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/voting/app/src/screens/VoteDetail.js

Updates the deprecated props and updates the LocalIdentityBadge's popover action to include an icon and use the correct tag mode.
**TODO**

Finance, Tokens, Voting: update badges

---

apps/finance/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/finance/app/src/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js
apps/finance/app/src/components/LocalIdentityBadge/LocalLabelPopoverTitle.js
apps/token-manager/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/token-manager/app/src/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js
apps/token-manager/app/src/components/LocalIdentityBadge/LocalLabelPopoverTitle.js
apps/voting/app/src/components/AppBadge.js
apps/voting/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/voting/app/src/components/LocalIdentityBadge/LocalLabelAppBadge.js
apps/voting/app/src/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js
apps/voting/app/src/components/LocalIdentityBadge/LocalLabelPopoverTitle.js
apps/voting/app/src/components/VoteCard/VoteCard.js
apps/voting/app/src/components/VoteText.js
apps/voting/app/src/screens/VoteDetail.js

Also reorganizes the other apps' identity badges so they're consistent with Voting's.

Voting: add AppBadge

---

apps/finance/app/src/App.js

Fixes https://github.com/aragon/aragon/issues/834
The transaction linked in the issue would have worked with 431,885 gas (if all accounting periods were already transitioned, which I assume that was the case given that the gas estimate was 420k). In any case, the real amount of gas that is actually used is lower, but because of DelegateProxy's `FWD_GAS_LIMIT` the transaction needs extra gas that is not used. I created an issue on aragonOS to rethink this: https://github.com/aragon/aragonOS/issues/556
There's another factor that we are not taking into account in this estimate and that is if the transaction is the first one in the accounting period, 15k more gas are needed as there is [an extra slot that is changed from zero to non-zero](https://github.com/aragon/aragon-apps/blob/master/apps …

Finance: increase gas estimate for deposits

---

apps/finance/app/src/components/NewTransfer/Deposit.js

From https://github.com/aragon/aragon-apps/pull/929#discussion_r314504863
We will align on using "funds" rather than "tokens" when referring to both ETH and ERC20 tokens.

Finance: update mainnet warning copy

---

apps/agent/app/src/components/Transfers.js
apps/finance/app/src/components/Transfers.js
apps/token-manager/app/src/screens/Holders.js

Ref: https://github.com/aragon/aragon-ui/pull/594

Memoize DataView deps

---

apps/voting/app/src/hooks/useVotes.js

Partially fixes https://github.com/aragon/aragon-apps/issues/994 (`app.icon()` error).
The issue was caused by the dummy app object used for external targets, that was not including `icon()`.

Voting: support external apps as target

---

apps/token-manager/app/src/screens/Holders.js

Holders: set max width on smaller screens

---

apps/agent/contracts/Agent.sol
apps/finance/contracts/Finance.sol
apps/survey/contracts/Survey.sol
apps/token-manager/contracts/TokenManager.sol
apps/voting/contracts/Voting.sol

Even though it was fun to spot projects reusing or forking aragon contracts: https://github.com/search?q=SPDX-License-Identitifer&type=Code
But I thought it might be interesting to fix the misspelling, in case any automated script might eventually parse that header to show the license.
Related: https://github.com/aragon/aragonOS/pull/558

Replace Identifier misspelling in license headers

---

apps/voting/app/src/components/AutoLink.js
apps/voting/app/src/components/VoteCard/VoteCard.js
apps/voting/app/src/components/VoteText.js
apps/voting/app/src/screens/VoteDetail.js

Before (notice the scrollbars):
After:

Voting: fix a description overflow issue

---

apps/voting/app/src/components/VoteCard/VoteCard.js
apps/voting/app/src/hooks/useVotes.js
apps/voting/app/src/screens/VoteDetail.js

This change ensures `icon()` only gets called when it exists.
/cc @john-light

Voting: fix a crash that was happening in certain cases

---

apps/finance/app/src/components/Transfers.js
apps/token-manager/app/src/components/InfoBoxes.js
apps/voting/app/src/screens/VoteDetail.js

Fixes #1014.
It looks like we get unlucky sometimes, where `@aragon/api-react`'s hooks are not hydrated with data fast enough and their default state is used.
This change adds protections to accessing `network.type` from `useNetwork()`, to avoid causing the apps to error immediately.

Finance, Tokens, Voting: guard accesses to network.type

---

apps/token-manager/contracts/TokenManager.sol

Another small typo that we found while working on the CLI.
The `not` was displayed when tokens were transferable.
Thanks @0xGabi

TokenManager: fix initialize()'s radspec for transferability

---

apps/token-manager/app/src/App.js

Not strictly necessary with the normal app title, but it is a structure we can reuse on other apps too.
Before:
After:

Tokens: fix the text overflow in the header

---

apps/voting/app/package.json
apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js

Requires https://github.com/aragon/aragon.js/pull/405

Voting: app paths

---

apps/voting/app/src/components/VoteCard/VoteCard.js
apps/voting/app/src/components/VoteCard/VotedIndicator.js

VoteCard: add animation to you voted info

---

apps/agent/contracts/Agent.sol

Agent: fix radspec for execute with value

---

apps/finance/app/src/script.js

Fixes an issue with `vault.balance()` returning reverts.
Web3.js does not yet handle revert strings (see https://github.com/ethereum/web3.js/issues/1707), so when `vault.balance()` reverts with something like `SAFE_ERC_20_BALANCE_REVERTED` <sup>1</sup>, it currently gets reported as a _very large_ number.
This avoids asking the Vault for token balances and goes to the token directly. One could argue this is _better_, since the token should be the true source of information anyway.
<sup>1</sup> Error string in bytes:
`0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001c534146455f4552435f32305f42414c414e43455f524556455254454400000000`

Finance: ask token directly for vault balance

---

apps/finance/app/src/components/NewTransfer/Withdrawal.js
apps/finance/app/src/components/ToggleContent.js
apps/finance/app/src/components/assets/arrow.svg

The new SidePanel now unmounts its content when closed, so there is no need to reset the state internally anymore.
Also use useLayoutEffect() rather than setTimeout() to focus the text field.
- Use IconUp rather than a custom image.
- Use ButtonBase rather than a button.
- Move to a function component.
- Add a pressed state.
- Use the css prop.

Finance: app improvements

---

apps/token-manager/app/src/App.js
apps/token-manager/app/src/components/AppHeader.js
apps/token-manager/app/src/components/InfoBoxes.js

We were using `useTheme()` before Main was declared, leading to the theme not being reactive to the `appearance` set.
In general, I wonder if we should make it a rule that Main is used ahead of any other app logic, to avoid cases like this? For example, both Finance and Voting could fall into this trap if they were to use `useTheme()` in their App.js.

Tokens: fix dark mode header

---

apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js
apps/voting/app/src/components/NewVotePanel.js
apps/voting/app/src/components/VoteCard/VoteOptions.js
apps/voting/app/src/hooks/usePanelState.js
apps/voting/app/src/hooks/useVotes.js
apps/voting/app/src/screens/Votes.js
apps/voting/app/src/web3-utils.js

Things like an app's name come from IPFS, and may not be available all the time.
The importance of re-spec'ing the data structures involved with apps is becoming clearer, as it'll let us more clearly mark whether something is always going to be available or not from aragon.js.

Voting: avoid crashing when external app details are not loadable

---

apps/finance/app/package.json

@bpierre Reversing the build-time configuration change from https://github.com/aragon/aragon-apps/pull/1078.
Producing a build via `npm run build` in Finance is failing with a cryptic `Uncaught ReferenceError: module is not defined`.
Perhaps it's because we haven't published the tree-shaking enabled version of aragonUI yet?

Finance: disable tree-shaking

---

apps/agent/manifest.json

@Evalir These locations are a bit weird, but since we publish apps with a slightly different directory structure, we assume the meta folder lives in the published folder's root directory.
E.g. if you do:
```
❯ ipfs ls QmbxRT5KXXP37ce3ixBRUxjXxaMjk2ff7fj923c48XkDBr
QmfBKBqv51pshk6jVbFeF3XtNcG1rd1tzyLLpSwTt9dqWR 20920   BCC.a29566e8.png
QmW9XjtMy7uDL5orxv8N7QnT41Z2s5hESuphmVVbuPqSKJ 15589   agent_badge.4e35e27e.svg
Qme1BVNBgvRBcdvNE7kXQKqkyjdtQQh8u8vi2epAFrJiQX -       aragon-ui/
QmWdkK7VPKao9rtLgHshbsVnDiqRfg1FZdBbJv296WrYJb 22082   artifact.json
QmXvT1hHwyw96dmT6CVd6YSb77PXaiuxaBixUuJp5CibkG 61430   code.sol
QmPZzqpEqTgw21gHZgAdujPwX7c1Wwg6js29wzpEj1DJMR 368     index.html
QmbZyMF7TJ7XQzwoLYQp2eCCrEsCeZjTXQ4gwZZrS6UYe8 543     manifest.json
QmUk4tiWznXKRHckDiD1VGgifZJPy7tviCMNfV9QWUMfEr - …
```

Agent: fix screenshot location

---

apps/voting/app/src/screens/VoteDetail.js

Spring cleaning 🌸, closing [#1346](https://github.com/aragon/aragon/issues/1346) over at `aragon/aragon`.
> Your affinity for fixes is apparent. I'm confident you'll find a typo there as well.
Adds suggestion for the voting copy regarding approval & support by @john-light . Maybe we want a bit more discussion around it?

Voting: add support / approval copy suggestion

---

apps/voting/app/.prettierrc
apps/voting/app/src/screens/VoteDetail.js

Building over the discussion at #1110 .
Here's how it looks with the copy changes:

Voting: fix voting copy to fit one line & add tooltip

---

apps/voting/app/src/screens/VoteDetail.js

- Users are more likely to set `50%` support for simply majority rule, rather than the previous `51%`, so I'm changing this to avoid confusion among users about how to implement a simple majority rule.
- "token holders" -> "tokenholders" (which is the terminology we use in the user guide at help.aragon.org)
- Fix Minimum Approval description

Voting: quorum and support hint copy updates

---

apps/finance/app/src/components/Transfers.js
apps/finance/app/src/components/TransfersFilters.js
apps/finance/app/src/components/useFilteredTransfers.js
apps/finance/app/src/transfer-types.js

Closes #1100 .
Ports agent filtering to finance, using hooks and consolidating all state regarding the filters in the `useFilteredTransfers` hook. Minor modifications were made due to differences in the `script.js`, mainly in detecting the transaction type. (`Incoming`, or `Outgoing`)

Finance: port agent filtering to finance

---

apps/voting/app/src/hooks/useVotes.js

We were getting an error in the `LocalIdentityProvider` inside the wrapper because we had a race condition where the `currentApp` or `installedApps` were not resolved by the time we were rendering initial votes (and sending a null address into the local identity badges in)

Voting: fix race condition with currentApp address being null

---

apps/voting/app/src/components/VoteActions.js
apps/voting/app/src/hooks/useVotes.js
apps/voting/app/src/utils.js

This pr closes https://github.com/aragon/aragon/issues/1150.
Rather than aligning the dates to UTC, we've decided to keep the times local, as all the other filters (as well as apps, e.g. Finance) use local times.

Voting: use local date in warnings about tokens holded

---

apps/token-manager/app/src/components/InfoBoxes.js
apps/token-manager/app/src/screens/EmptyState.js
apps/token-manager/app/src/script.js
apps/token-manager/test/tokenmanager.js

See https://github.com/aragon/aragon-apps/pull/1117.

Tokens: update terminology to prefer 'tokenholder'

---

apps/voting/app/src/components/VoteCast.js
apps/voting/app/src/screens/VoteDetail.js
apps/voting/app/src/script.js

See https://github.com/aragon/aragon-apps/issues/1118.

Voting: update terminology to prefer 'cast'

---

apps/finance/app/src/components/Transfers.js
apps/finance/app/src/components/useDownloadData.js
apps/finance/app/src/lib/date-utils.js

Builds on #1102 (should be merged first) , closes #1087 .
Adds an useDownloadData hook that builds the CSV on demand, properly formatting it to fit the finance usage. Ported over from the Agent implementation.

Finance: add useDownloadData hook

---

apps/voting/app/src/screens/VoteDetail.js

Oops, I thought https://github.com/aragon/aragon-apps/pull/1114 had covered this case, but it looks like this uses a different format!

Voting: fix UTC still being present in VoteDetail

---

apps/voting/app/src/components/VoteText.js

Similar to https://github.com/aragon/aragon/pull/1426.
AFAIK there's no change being rendered; we updated the `AddressBadge`'s compact mode to include the spacing.

Voting: update VoteText's address rendering

---

apps/finance/app/src/components/AmountInput.js
apps/finance/app/src/components/NewTransfer/Deposit.js
apps/finance/app/src/components/NewTransfer/Withdrawal.js
apps/token-manager/app/src/components/AmountInput.js
apps/token-manager/app/src/components/UpdateTokenPanel/UpdateTokenPanel.js

Closes https://github.com/aragon/aragon/issues/1301
It adds 'MAX' button for selecting max amount available. The button is added on these sections: 
**Concerns**
1. I can't input for selecting an amount on the agent app (
According to the description of the issue, there should be).
2. I'm not sure about test strategy on this repo so PR hasn't tested.

Finance, Token Manager: Forms MAX button 

---

apps/voting/scripts/buidler-hooks.js

The app was initializing with the `tokens` app address rather than the `minime` token address.

Voting: fix init params on Buidler plugin

---

apps/agent/app/.babelrc
apps/agent/app/package.json
apps/finance/app/.babelrc
apps/finance/app/package.json

Similar to https://github.com/aragon/aragon/pull/1434, Agent/Finance's frontend builds were failing due to the new release causing babel plugin clashes.
Only a problem for these apps as the others have not upgraded to babel@7 yet 🙈.

Agent, Finance: update babel configuration

---

apps/agent/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/agent/app/src/components/LocalIdentityBadge/LocalLabelPopoverActionLabel.js
apps/agent/app/src/components/LocalIdentityBadge/LocalLabelPopoverTitle.js
apps/agent/app/src/components/useFilteredTransactions.js
apps/agent/app/src/script.js
apps/finance/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/token-manager/app/src/components/InfoBoxes.js
apps/token-manager/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js
apps/token-manager/app/src/components/You.js
apps/token-manager/app/src/screens/Holders.js
apps/voting/app/src/components/LocalIdentityBadge/LocalIdentityBadge.js

This PR  closes  #1008 
With long custom labels it looks like this:

Tokens: Fix hidden you pill on sidebar

---

apps/survey/app/.prettierrc
apps/token-manager/app/.prettierrc

This configuration was missing, I've added them for consistency.

Survey, Token Manager: add prettier config

---

apps/token-manager/app/src/screens/Holders.js

It doesn't make sense to display this value if the user either doesn't have any vestings, or if they've all finished vesting already.

Tokens: avoid displaying locked balance if no tokens are locked

---

apps/voting/app/src/App.js
apps/voting/app/src/app-logic.js
apps/voting/app/src/identity-manager.js
apps/voting/app/src/index.js

<AragonApi /> has moved to index.js and is now the root component. It fixes an issue where the devserver autoreload would prevent the aragonAPI connection to restore properly. The issue seems to only appear when <AragonApi /> is not the root component. I will investigate separately on the side of aragonAPI for React.
It also aligns the Voting app with the other apps in that regard.

Voting: fix dev server autoreload

---

apps/voting/app/src/screens/VoteDetail.js
apps/voting/app/src/screens/Votes.js

Voting: migrate date format to ISO-8601

---

apps/token-manager/app/src/screens/Holders.js

Moves renderEntry hook calls and & UI depending on these into its own component, to avoid breaking the rules of hooks. Fixes #1170 
Right now there's a bug that's breaking Token Manager apps with more than 10 holders (the pagination threshold) live on Mainnet; when switching to the last tab, a React error will appear, saying that a different amount of hooks were rendered, compared to the previous render. This breaks the rules of hooks, and subsequently, the app throws.
The reason this happens is actually documented on the [aragonUI docs](https://ui.aragon.org/data-view/) for the `DataView` component: the props marked with `render` should never hold hooks as they're called conditionally. The solution is to move the breaking parts of this function to a component.

Tokens: Move renderEntry hook calls into its own component & fix crash

---

apps/finance/app/.babelrc
apps/finance/app/package.json
apps/finance/app/src/components/Balances.js
apps/finance/app/src/components/useConvertRates.js
apps/finance/app/src/lib/conversion-utils.js
apps/finance/app/src/lib/conversion-utils.test.js

Fixes a problem that arose with the move to using [bn.js everywhere](https://github.com/aragon/aragon-apps/commit/b90ebc47c722dcfa16b74b2fc7a9ec12193adb8f#diff-e842cf2b89a742592b21eeebff9f7086R79), where the conversion from Token Amount to USD was being done incorrectly, as bn.js itself can't handle decimals, and they were being passed onto the function. This adds a few things:
- A function to "shift" numbers a certain amount of decimals safely and counting the amount of places it was shifted (`toDecimal` and `fromDecimal` exist, but required a bit of hacking to make them work for this, so I implemented another version)
- A function to transform the passed token taking into account its decimals and the exchange rate correctly, using just bn.js and not relying on pure Javascript numbers.
- …

Fix finance USD conversion mechanism

---

apps/agent/contracts/Agent.sol
apps/agent/contracts/standards/IERC1155Receiver.sol
apps/agent/contracts/standards/IERC165.sol
apps/agent/contracts/standards/IERC721Receiver.sol
apps/agent/test/agent_shared.js

Adds support for [ERC-1155 tokens](https://eips.ethereum.org/EIPS/eip-1155) to the Agent.
Also found a couple other things I've updated with this change:
- When uninitialized, report false for ERC-165, ERC-721, and ERC-1155
- Update docstrings / code style for ERC interfaces to closely match their finalized states on eip.org

Agent: support ERC-1155

---

apps/agent/app/src/components/Transactions.js
apps/agent/app/src/components/useFilteredTransactions.js

Addresses the first 3 points of the pending [Agent](https://github.com/aragon/aragon-apps/issues/1120) upgrades.

Agent: Filtering Updates

---

apps/agent/app/src/components/BalanceToken.js
apps/agent/app/src/components/Balances.js
apps/agent/app/src/components/useConvertRates.js
apps/agent/app/src/lib/conversion-utils.js
apps/agent/app/src/lib/conversion-utils.test.js

Replicates conversion strategy used in #1177.

Agent: replicate rate conversion strategy from #1177

---

apps/token-manager/app/src/App.js
apps/voting/app/src/App.js

Seems we hadn't updated the Token Manager app for allocating the correct spacing in between the sync indicator and the helpscout icon.
Before:
After:

Tokens: Fix token SyncIndicator position

---

apps/agreement/contracts/Agreement.sol
apps/agreement/contracts/test/mocks/disputable/DisputableAppMock.sol
apps/agreement/test/agreement/agreement_close.js
apps/agreement/test/helpers/wrappers/disputable.js

Related to https://github.com/aragon/aragonOS/pull/594
This PRs improve the `close` function of the Agreement app to avoid calling `canClose` if the sender is the disputable app

Agreement: Improve can close check for disputables

---

apps/vault/test/vault_shared.js

Unskips a test skipped in https://github.com/aragon/aragon-apps/pull/1218.
@facuspagnuolo I think you must've been using an old version of the `@aragon/os` dependency locally.
We should see this pass on CI.

Vault: unskip test

---

apps/voting-disputable/contracts/DisputableVoting.sol
apps/voting-disputable/package.json
apps/voting-disputable/test/contracts/voting_create.js
apps/voting-disputable/test/contracts/voting_disputable.js
apps/voting-disputable/test/contracts/voting_gas_costs.js
apps/voting-disputable/test/helpers/deployer.js

This PR changes the way `canForward` was computed basically:
- Pass the original sender by parameter
- Check the agreement was set
This PR also updates the `disputable_voting_app` branch with the last changes from `master`, it is recommended to review only the last two commits.

DisputableVoting: Rollback ACL v2 related changes

---

apps/voting-disputable/README.md
apps/voting-disputable/manifest.json
apps/voting-disputable/package.json

Adds some notes about the frontend's development and removes the old publish scripts for now.

DisputableVoting: avoid publishing Client-based frontend to aragonPM

---

apps/agent/buidler.config.js
apps/agreement/buidler.config.js
apps/finance/buidler.config.js
apps/token-manager/buidler.config.js
apps/vault/buidler.config.js
apps/voting-disputable/buidler.config.js
apps/voting/buidler.config.js

Strips these configs of keys, and uses `ETH_KEYS` instead. It didn't make much sense to default to the aragen default on rinkeby/mainnet in most cases anyway, since you would never want to use those in a real environment.
`ETH_KEYS` supports one or more comma-delinated keys.

Apps: update buidler config and remove keys

---

apps/agreement/contracts/Agreement.sol
apps/agreement/test/agreement/agreement_dispute.js

@sohkai I noticed Aragon Court actually allows you to close the evidence period automatically, would you support this or do we prefer not to avoid risks on bricking disputes?

Agreement: Close evidence period automatically

---

apps/agent/app/src/components/Transactions.js
apps/finance/app/src/components/Transfers.js

@sohkai could you please check in Safari just to be sure? (I can only do Gecko / Blink)
Fixes https://github.com/aragon/aragon/issues/1212.

Finance: fix transfers layout (text overflow)

---

apps/voting-disputable/contracts/DisputableVoting.sol

The main reason is that Disputable Voting apps won't be able to control the agreement's settings otherwise

DisputableVoting: Remove agreement from executors blacklist

---

.github/deploy.yml

Adds new workflow to publish an app based on the tag name.
It automatically creates a new Release on Github, pushes the new version to APM and adds the bundle to aragon/deployments
The tag format is fixed and works hand in hand with the release workflow.
Format: `VERSION-APP-NETWORK` e.g.: `2.5.15-voting-matic`

[cicd] adds workflow to build, deploy and release on a tag

---

.github/release.yml

The new workflow automatically creates new Github Releases in this repo for the apps mentioned in the labels of the merged pull request.
The workflow only runs if the pull request is merged to the `master` branch and only adds new releases for the apps mentioned in the labels.
It also automatically bumps the version number of the app by the level also configured in the tags.
It **does not** publish the release to the apm registry. It only runs the dry run method to get the ipfs hash and the apm version number.
New Github Releases will be created per chain (mainnet, rinkeby, mumbai, polygon) and app.
A pull request with the labels `voting:patch` and `token-manager:major` gets merged to the master branch.
Then the workflow will create 4 new Github Releases for voting with the new version …

[cicd] adds auto release workflow

---

apps/token-manager/contracts/TokenManager.sol

Pay attention, the @notice parameter of the assignVested method in the TokenManagercontract breaks theradspec` parser: there is a infinity loop.
Context: https://github.com/aragon/radspec/pull/127

fix assignVested notice
